### ISSUE TITLE
flavor分けの対応

### ISSUE THREAD

**Issue by pj-picbook** [pj-picbook/picbook#102]
## 概要

- devとprdで環境分け
- タスクとして積んでPRを作っておいて、良きタイミングでマージする

## 要件
https://flutteruniv.slack.com/archives/C03PARB9W1F/p1660479982540249

## 期限

- 2020/08/23

## 親ストーリー
なし

**Comment by kawadon780** [comment]
@karokita @tokku5552 @Romu1273x @Ta23ka98 

**本課題で基本的にやる事**


・ReadMeを更新（ビルドコマンドを載せる、flvorの使い方とか）

・flavor引数でgogleservice系のファイルをdevとprodで切り替える

・androidの変更項目は「パッケージ名」「署名」くらいだが、prodに関しては「proguard」をONにしていいかも。
proguardについてはこちら
https://developer.android.com/studio/build/shrink-code?hl=j

・iOSはxconfigとかのビルド設定を行う



**ってイメージなのでやまさんにお願いする作業が以下の様に発生するかも。**


・firebaseのprod（本番、製品用の環境）を作る。もしくはもうできてるなら私の方に共有と権限付与。
ないのであればバンドル名およびパッケージ名を決めて、Firestoreなどの設定が必要であればRomさん？（徳田さんだったかも）作業を依頼する。

・iOSの署名に必要なプロビジョニングファイルと秘密鍵を渡しに共有（ビルド作業に必要）**

**Comment by tokku5552** [comment]
> firebaseのprod（本番、製品用の環境）を作る。もしくはもうできてるなら私の方に共有と権限付与。
ないのであればバンドル名およびパッケージ名を決めて、Firestoreなどの設定が必要であればRomさん？（徳田さんだったかも）作業を依頼する。

今プロジェクト見てみましたが、pj-pickbook-proにすでに @kawadon780 編集者として入ってます！&Firestoreの設定はオーナーしかできなくて、proの方は @karokita にやっていただくことになるかもです！

**Comment by tokku5552** [comment]
あと、ところどころ古いし、このやり方が最適かどうかは微妙ですが、私がいつも脳死でやるときはこの記事ほとんどそのままやってます！
https://qiita.com/tokkun5552/items/cd70c65dd06935d8c751

**Comment by karokita** [comment]
かわどさん、徳田さん、ありがとうございますー！
まず、1個目のfirebaseのprod（本番、製品用の環境）を作る、についてです。

**◎firebaseのprodについて**　（→ @kawadon780 )
firebaseのprod環境については、徳田さんからコメントいただいたようにかわどさんを編集者として、招待しています！名前ちょっと混乱するかもですが、下記となっています。
【pj-picbook-dev】「pj-picbook-pro」　（いつも使ってるプロジェクト）
【pj-picbook-pro】「pj-picbook」

**◎proの方のfirebase設定について** （→@kawadon780 @tokku5552 )
あ〜proは確か、設定してないので設定が必要になりますね！devの時にやったタスクとしてはここが当たりそうでしょうか？
https://github.com/pj-picbook/picbook/issues/5

今、テストフライト用のアーカイブビルドに絶賛詰まっているので、もしどなたか手空いてる方いたら、オーナー権限を一時的に付与&対応いただくとかもありかなと思ったりしましたがいかがでしょうか？

もしくは次のコメントに絡みますが、今回の環境分けの作業でかわどさんにアーカイブ作成やっていただくことになりそうであれば、一旦こちらのfirestoreの設定を先行して着手できます！（トンチンカンなこと言ってたらすみません！

**Comment by karokita** [comment]
共有系についてです！  (→ @kawadon780 ) 

>iOSのビルドに必要なプロビジョニングファイルと秘密鍵を私に共有。この作業もしかしたらムズイのでそん時は私に確認。

一応プロビジョニングファイルは手元にあります！＆秘密鍵の発行も以前やってことがあったので大丈夫そうです。
お手数をおかけしますが、秘密鍵についてどの工程で使うのかを教えていただいても良いでしょうか？
参考になりそうなドキュメントとかあったら共有いただけると助かります！

流れを理解した上で共有できると良いな、と思いました🙏

**Comment by kawadon780** [comment]
@tokku5552 @karokita 
こちらFirebaseの本番確認できました！単に一回も表示してなかったから一覧にでてなかっただけでしたorz

> あと、ところどころ古いし、このやり方が最適かどうかは微妙ですが、私がいつも脳死でやるときはこの記事ほとんどそのままやってます！
https://qiita.com/tokkun5552/items/cd70c65dd06935d8c751

こちらありがとうございます！参考にして作業してみます！

> オーナー権限を一時的に付与&対応いただくとかもありかなと思ったりしましたがいかがでしょうか？

こちら問題ない気がします～。Firestoreの設定周り恐らくですが以下のissue周りかと思います。
https://github.com/pj-picbook/picbook/issues/46
https://github.com/pj-picbook/picbook/issues/88


セキュリティルールとかはコピペでいけるならやってしまっていいのであれば依頼するほどじゃないのかな？徳田さんに聞いた方がいいかも。

**Comment by tokku5552** [comment]
セキュリティルールはGitHub Actionsから自動でやればいいので、そこのつなぎの設定だけやってもらえればいいかなと思います！

**Comment by tokku5552** [comment]
これを気にやまさんのアカウントでトークン再発行してシークレットに入れてもらえばいいかなと！

https://github.com/marketplace/actions/deploy-to-firebase

**Comment by kawadon780** [comment]
@karokita 

> お手数をおかけしますが、秘密鍵についてどの工程で使うのかを教えていただいても良いでしょうか？

すみません勘違いで、appstoreへアップロードの際にいるかなーと思ったのですが、もしかしたら必要ないかもです！
というかstoreへのアップロード自体はやまさんにしてもらえればよさそうだし、鍵（cetificate、拡張子がcerのやつ）は一旦いらないです～。
証明書も開発者登録してもらえれば多分自分でDLできる？と思うので、山さんの方から自分に何かファイル共有する作業は一旦いらなそうです。

とりあえず一つ一つ課題を解決するとして、「開発のビルドができる」様にしたいです。（ipaファイル生成）
以下の様な作業が必要そうです。
https://www.zaico.co.jp/engineer/apple-developer-program-howto-add-member/

証明書とUDIDはDMで後ほど共有します！（あまりpublicな場所に残したくないので）

**Comment by karokita** [comment]
@kawadon780 @tokku5552 
無事githubのシークレットにfirebaseトークン入れられました。
ありがとうございます！

ここから先はかわどさんにご対応いただく流れでよさそうでしょうか？
他必要なことありましたらお知らせください。

**Comment by karokita** [comment]
@kawadon780 

秘密鍵いらない旨、承知です！
証明書とUUIDお待ちしております〜

**Comment by kawadon780** [comment]
@karokita 
はいー、とりあえず正常にfirest
ore使えれば問題ない認識です。

androidから先にprodの環境で正常に動く事を確認予定です。（flavor分けしてビルドしたapkが正常に動くまでをテスト）

**Comment by kawadon780** [comment]
@karokita 
すみません、prodのバンドル名およびパッケージ名って何か予定ありますでしょうか？
現状devは「com.example.picbook」という名前になっています。（exampleでよかったのかは謎）


prodはまだandroidもiOSもFirebase上にアプリが作成されてないみたいです。
こちらバンドル名決まれば私の方で作成する事も可能です。

**Comment by kawadon780** [comment]
@karokita 
質問しといてあれですが、とりあえず「com.example.picbook.prod」とか適当にこっちで作ってみます！。

**Comment by karokita** [comment]
@kawadon780 レス遅れました！バンドル名変更厳しそうなので、com.picbook.prodでいかがでしょうか？？

**Comment by karokita** [comment]
@kawadon780 
いえいえです。
今絶賛エラー出てるので、調べてたらレス遅れてしまった感じでした笑
なにとぞなにとぞ！
