### ISSUE TITLE
エラー対応

### ISSUE THREAD

**Issue by karokita** [pj-picbook/picbook#113]
## 概要

- エラー対応

## 要件

- ログをキャッチできるようにする 
  - Crashlytics、センチュリーなど
- Authentication周りのエラーハンドリング
  - https://docs.google.com/spreadsheets/d/1CK5Tu0aNuPku_3PjVD7hDYOufhr_6osbX3BM-0jNj4Y/edit?usp=sharing

**Comment by Ta23ka98** [comment]
@tokku5552 
[Crashlyticsのドキュメント](https://firebase.google.com/docs/crashlytics/customize-crash-reports?hl=ja&platform=flutter)を一通り理解したと思うので、認識をすり合わせておきたいです🙋
(あとテストクラッシュを意図的に発生させ、Firebaseコンソールで確認も出来ました)

Crashlyticsによって...
・Flutter内、外、あるいは特定のゾーンで発生したエラーを報告する
・カスタムキー、カスタムログ設定によって、エラーの詳細がわかるようにする
こんな感じでしょうか🤔

あとiOSとAndroid向けのセットアップ(?)について、[人が読める形式のクラッシュレポートを取得する](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?hl=ja&platform=flutter)が必要そうです。
Firebase CLIについて詳しくないのですが、とりあえず #46 を参考にセットアップを進めようと思います。

**Comment by tokku5552** [comment]
@tokku5552 
とりあえず組み込んでおくだけでいいかなと思います！それよりもAuthenticationのエラーハンドリングの方が緊急度としては高いかなと思います 🤔 

もちろんさくっと出来そうならそこまでやっていただいたほうがありがたいです 🙏

**Comment by Ta23ka98** [comment]
@tokku5552 
了解です！
とりあえず、先にAuthenticationの方に取り掛かりたいと思います🙋

**Comment by Ta23ka98** [comment]
@karokita
Authのエラーハンドリングについて、2点ほど確認したいです🙋

①対応するエラーは、スプレッドシートのエラーのみ？
②Authエラーの表示方法
・UIにTextウィジェットを追加し、そこで表示する？(ログイン画面、会員登録画面など)
・あるいは[SnackBar](https://docs.flutter.dev/cookbook/design/snackbars)などで表示する？

**Comment by karokita** [comment]
@Ta23ka98 
はい！

①スプレッドシートの対応エラーとかいたタブのみで大丈夫です。
②SnackBar表示でお願いします🙏

**Comment by Ta23ka98** [comment]
@tokku5552 
色々とやり方を模索してみましたが、AuthのエラーハンドリングとsnackBar表示を両立させる方法が分かりませんでした...
何か良い方法があればアドバイスをお願いしたいです🙇

質問ZoomにてAoiさんに「rethrowを使ってみては」とアドバイス頂いているので、今はひとまずそちらを試しています。

これまで試した方法としては...
①AuthExceptionでエラーが出たタイミングでsnackBarを表示してみる
・contextが上手く取得できず、失敗
(GlobalKeyもuseContextも上手くいかない)

②ref.listenとStateProvider、エラー発生時にstateをcopyWithする
・AuthRepositoryからはViewModelのstateは変更できないので失敗

＊今は②をstateではなく、rethrowでViewModelにエラーを投げようと考えています

**Comment by tokku5552** [comment]
どこかしらでExceptionをキャッチしてメッセージに書き変えてrethrowするのがいいと思います。
基本はAuthRepositoryかnotifierでメッセージに変換した後throwして、view側でcatchしてsnackbar表示になるかなと思います。
couple_todoでは https://github.com/flutteruniv/couple_todo/blob/main/lib/presentation/signup/signup_model.dart#L106 でエラーメッセージを変換して https://github.com/flutteruniv/couple_todo/blob/main/lib/presentation/signup/signup_page.dart#L90 ここでcatchしたものをsnackbarに表示しています。

**Comment by Ta23ka98** [comment]
@tokku5552 
ありがとうございます、参考にさせて頂きます🙌
