### ISSUE TITLE
登録した絵本の冊数がマイページ上でカウントされない

### ISSUE THREAD

**Issue by karokita** [pj-picbook/picbook#121]
## 概要

登録した絵本の冊数がマイページでカウントされない

## 詳細

登録した絵本の冊数がマイページでカウントされない

## 関連タスク(任意)
https://github.com/pj-picbook/picbook/issues/86

**Comment by karokita** [comment]
@Romu1273x 

先ほど出たタスクをアサインさせていただきました！

[やること]
- bookshelfHistoriesのデータではなく、booksデータからカウントする
　https://github.com/pj-picbook/picbook/blob/develop/docs/schema_firebase.yml
- book_notifireを使う
- カウントされたデータをマイページで表示させる

※暫定対応となるので、わかり易い形でドキュメントに残しておく
※対応の理由はbookshelfHistoriesを準備するのに手間がかかるため

**Comment by Romu1273x** [comment]
developにマージ済み
