### ISSUE TITLE
Crashlyticsによるエラー対応

### ISSUE THREAD

**Issue by Ta23ka98** [pj-picbook/picbook#126]
## 概要

- Crashlyticsによるエラー対応

## 要件

 - ログをキャッチできるようにする

**Comment by Ta23ka98** [comment]
@karokita 
Crashlyricsの設定をしたいのですが、リポジトリ名がどっちか忘れてしまいました😅
どちらが開発用のリポジトリだったか教えて頂きたいです🙇
<img width="1026" alt="スクリーンショット 2022-08-31 19 53 49" src="https://user-images.githubusercontent.com/79580546/187662817-e3159510-4814-4dbb-88a9-4c13533c7ab6.png">

**Comment by karokita** [comment]
@Ta23ka98 
紛らわしいですね😂
すみません！

dev：pj-picbook-pro
pro：pj-picbook

になります。

**Comment by Ta23ka98** [comment]
@karokita 
了解です！
ありがとうございます🙌

**Comment by Ta23ka98** [comment]
@karokita 
改めてこのissueの要件を詰めたいです🙋
とりあえず現在、アプリが問答無用でクラッシュした等のレポートは送られるみたいです。

他にCrashlyticsの機能として、"致命的でないエラー"を送信するように実装することも可能です。
(例えばログイン・会員登録で「ユーザが見つかりません」などの小さいエラー)

もしこれらに対応する場合、「どういうエラーに対応するか」を決める必要が出てくると思います🤔

**Comment by karokita** [comment]
@Ta23ka98 

おお、クラッシュした際のレポート送られるようになったんですね。ありがとうございます！

一旦、初期はユーザー数などを考えていくと
クラッシュした内容を送れるというとこまでissue closeが良いかなと思いました！

ちなみに見方としては、コンソール→crashlyticsで見れる感じでしょうか？

**Comment by Ta23ka98** [comment]
@karokita 
一旦closeは了解しました！🙌
Androidでは確認できていないので、エミュレータでも確認次第プルリク出そうと思います。

おっしゃる通り、Crashlyticsはこんな感じで見れます👍
<img width="1433" alt="スクリーンショット 2022-09-03 20 43 57" src="https://user-images.githubusercontent.com/79580546/188268920-7cad3a96-5ab0-4390-87ae-96c65c50975c.png">

**Comment by karokita** [comment]
@Ta23ka98 
おおお、見れました！！！
見てる感じだとどのファイルのどの行でクラッシュしてるかがとれるんですかね...🤔

データ量が多くなったり、ユーザー数が多くなるとクラッシュデータ取れるの大事になってくると思うので、
まずはCrashlytics入れられてよかったなと思いました！

Androidでのご確認、よろしくお願いします🙋‍♀️

**Comment by Ta23ka98** [comment]
@karokita 
Androidでのクラッシュも確認できたので、プルリク作成しました！

未解決の課題(致命的でないエラーへの対応)があるので、一応チェックボックスを空欄にしてあります。
「現時点でissue作成は不要だからチェック」/あるいは「後で作成するので未チェック」の判断はお任せします🙇

クラッシュの種類については、上から順に
①Flutter：たぶん▶️ボタンで再起動した報告
②first_page, line??：FirstPageでテストクラッシュを確認した時の報告と、その行数
③signup_notifier, line：お試しで"致命的でないエラー"(会員登録できなかったエラー)を確認した時の報告
という感じだと思います👍

[ドキュメント](https://firebase.google.com/docs/crashlytics/customize-crash-reports?hl=ja&platform=flutter#add-logs)曰く、カスタムメッセージを設定すればどのようなエラーかが簡単に可視化できるようです
(あと③についてはお試しなので、コミットせずプルリクにも反映されていない感じです)

**Comment by karokita** [comment]
@Ta23ka98 

一旦issue立ててみましたので、チェックボックスお願いします🙋‍♀️
また、丁寧に説明いただいてありがとうございます〜！

crashlyticsのダッシュボードの下の画面の問題のところで、新規/解決済みみたいな項目があったので、
何かエラーをキャッチして、それを解消する運用までをcrashlyticsでやっていくイメージなんですかね...🤔

キャッチしたいエラーとどう使っていくかを想像しつつ、パターン出しできると良さそうですね！

**Comment by Ta23ka98** [comment]
こちらマージ済みなのでクローズしておきます🙋
