### ISSUE TITLE
マイページ

### ISSUE THREAD

**Issue by tokku5552** [pj-picbook/picbook#13]
## 概要

![スクリーンショット 2022-07-23 17 21 50](https://user-images.githubusercontent.com/96728192/180597003-d6b01466-e64f-47c3-9c6c-7c85460d5128.png)

マイページ

## 詳細

- ユーザー情報
  - アイコン
  - 最初はランダム3種類の中からアイコンが表示される（Twitterの卵マーク的な）
  - ユーザーが写真を登録できる
  - なまえ
  - 登録した名前が表示
  - よんだえほん
  - 読んだ絵本の冊数が表示
  - 年齢
  - 年齢が表示
  - 登録日
  - 登録した日にちが表示
- 設定
  - 登録情報の設定
  - ログアウト

## 要件

- ここに要件を列挙する
  - こんな感じ

MEMO
https://www.youtube.com/watch?v=4tG8M4wK4F0

## 期限

- 2020/07/26

## タスク一覧

- #29 
- #30

**Comment by tokku5552** [comment]
- 画面の仕様変更に伴う変更点
  - 登録日と年齢を保持しておく必要がある。
  - どちらも大した変更ではなさそう。
- 年齢について
  - ユーザー(大人)に対して子供が複数いるという前提だった気がするが変わった？

**Comment by karokita** [comment]
@tokku5552 
ご質問いただいてたので誰担当するかは置いておいて、現在考えてる仕様をお伝えします！

- 変更点として登録日と年齢を保持しておく必要があるというのその通りになります。大した変更じゃない旨、よかったです〜。

- 年齢について
  - ユーザー(1アカウント）に対して子供が複数いる前提であっています。
  - ここはMTGでご相談できればと思ってたのですが、Instagramのアカウント生成の考え方でいけないかなと考えてまして。
    - Instagramでは、最初にアカウントを作成するとき、メールアドレスなどが必要で、諸々登録するとアカウントが作成されます。一度情報を登録すると以降2アカウント目はメアドの登録がなく作れます。
    -  https://appllio.com/instagram-multi-account-login
  -  なので、初回の登録画面での情報を入力したタイミングで
  - 一つ目の本棚が自動生成される→（名前と年齢）は、1つ目の本棚に送れる
  - とベストというイメージでいました。
  - とはいえ、こういうデータの送り方が可能なのかが見えてなかったので、ご意見お伺いしたいです！
 
<img width="679" alt="スクリーンショット 2022-08-05 0 25 27" src="https://user-images.githubusercontent.com/96728192/182885760-9ba969ff-aacd-4881-bc29-ac01352079de.png">

 @kawadon780 @Romu1273x @Ta23ka98 
 新規登録と本棚生成の関係についてご不明点あればご意見いただければと思います🙌

**Comment by tokku5552** [comment]
つまり年齢は本棚に紐づくということですかね？MTGなりどこかで再度モデリングしましょう 👍

**Comment by tokku5552** [comment]
こちら詳細を詰めたほうが良さそうですが、現時点で以下の疑問が出ました。
- 1本棚=1子供でOK？1人の子供が複数の本棚を持てる？
- 本棚と子供を紐付けて複数管理したいのであれば、picbookのアカウント(親、これはユニークでなければならない)の情報をマイページに表示するわけではない？読んだ絵本、ねんれいは誰の情報？最初に登録した子供？それともアカウントに紐づく冊数の合計？特にねんれいはだれ？(親のねんれいを表示したいわけではないと思うので笑)
- 読んだ回数と本棚の登録は別の可能性がある？
  - 例えばAという本をaくんの本棚に登録した場合、その本はbちゃんの本棚にも表示されてほしい？(実際には家にAという本があるはずなので)
  - aくんは読んだけどbちゃんは読んでいないという状況は発生しそう
  - これを共有しない場合、両方の本棚に登録するために例えばバーコードを2回読み取る必要が出てきてしまう。

**Comment by karokita** [comment]
徳田さんからいただいたご質問への返答です。太字にしてます！

- 1本棚=1子供でOK？1人の子供が複数の本棚を持てる？
  - **1本棚=1子供です。1人の子供は複数の本棚持てないです。（本棚を新規作成はできるが、別の子供がいることになる）**
- 本棚と子供を紐付けて複数管理したいのであれば、picbookのアカウント(親、これはユニークでなければならない)の情報をマイページに表示するわけではない？読んだ絵本、ねんれいは誰の情報？最初に登録した子供？それともアカウントに紐づく冊数の合計？特にねんれいはだれ？(親のねんれいを表示したいわけではないと思うので笑)
  - **これは、本棚を追加できる機能ができたら、変わります！本棚を追加できる機能ができたら、アカウントと本棚1:nになるので、見せ方を変えますが、追加できる機能ができる前はアカウントと本棚が1:1なので、マイページに表示させるが良いと思ってます。年齢は敢えて子供と強調しないようにしてます。子供向けの利用想定ではあるのですが、初期絵本好きの大人にも使い勝手聞いてみようと思ってるので、本棚を使う人の年齢を入力するイメージでした。**
- 読んだ回数と本棚の登録は別の可能性がある？
  - 例えばAという本をaくんの本棚に登録した場合、その本はbちゃんの本棚にも表示されてほしい？(実際には家にAという本があるはずなので)
    - **これはないです。bちゃんの本棚に表示させる場合は、別途新規登録の工程を踏むことになります。**
  - aくんは読んだけどbちゃんは読んでいないという状況は発生しそう
  - これを共有しない場合、両方の本棚に登録するために例えばバーコードを2回読み取る必要が出てきてしまう。
     - **両方の本棚に登録するために、バーコードを2回読み取る（or検索する）、で正です！子供自身が登録する想定もしているので、一通り自分自身で登録する行為を行うことで自分でやったという充実感を感じてもらいたいです。そして一家の中の子供が双子とかじゃない限りは、読む絵本が変わるので(読む時に選ぶ絵本の対象年齢が変わる）、結局登録する絵本も変わるかなと思ってます！**

**Comment by Ta23ka98** [comment]
個人的には、１アカウント=１家族 =１本棚の方がいいと思います🙋
というのも...
- この仕様をユーザに理解してもらうことが難しい
- 現実的に、仕様通りに使ってもらうことが難しい
- この仕様の実装が難しい
からです。

徳田さんに出して頂いた疑問についても、
> 本棚と子供を紐づけて管理するなら...云々

・マイページ：親のアカウントを表示
・本棚：１つだけ用意する。(そもそも子供ごとに管理しない)
・「誰が、どの本棚の本を読んだ？」：管理しない
という方がいいと思います。

そもそも、子供ごとの本棚/誰が読んだか/読んだ回数を管理するメリットがあまり無いように感じます🤔
(今後の機能追加に向けての実装だと思いますが...)

また現実的に考えて、「子供Aが子供Bの本棚(の本)を読んでしまうことを、完全には防げない」と思います。
(誰でもすべての本棚にアクセスできてしまうので)

**Comment by karokita** [comment]
@Ta23ka98 
ご意見ありがとうございます！

仕様の理解が難しい、については例えばなのですがネットフリックスのアカウント切り替えのような形でUIを整理してあげることで回避できることかな、と思います！あとはチュートリアルなど、色々やり方はあると思ってます。難しい複雑なものをいかに直感的にわかりやすくできるかどうかがサービスを企画するときの頭の絞りどころかなと思ってます。
![6171_11](https://user-images.githubusercontent.com/96728192/183235320-e1edc41e-5e93-4cb5-bb8d-b6f9f3867ad2.jpeg)

子供Aが子供Bの本を読むことを防げない、については例えば、合言葉みたいなのを設けて好きな言葉を子供に入力させる、みたいな工程を踏むとか、何か色々やり方はあると思います。あと自分の名前のとこに、ログがたまってく、っていうのが喜びポイントだと思うので、積極的に自分のアカウントで記録したくなるような演出をしたいと思ってます。

子供の本棚、誰が読んだか、読んだ回数を管理するに関しては、ログで可視化することで、モチベーションアップやより読書意欲が促進するだろうというのが根本にあるので、そこはかなり大事な部分ですね。夏休みのラジオ体操カード的な。逆にメリットないな、と感じてしまうということはまだ説明が行き届いてないのかも...と思いました。ちょっとここは大事な部分なので、定例かどこかgatherでお話ししたいです！

仕様の実装が難しい、については確かにありそうだなと思ったので、現実的に可能な範囲でスペックを切ったり落としたり、という対応にはなるかなと思います！ここは火曜日お話ししたいです。

難しいベースで考えて大事な部分削ってしまうと存在する意味なし作る意味なしなアプリになっちゃうので、大事なところは持ちつつ、実現可能な範囲で落としていきたいです。

**Comment by tokku5552** [comment]
> 1本棚=1子供でOK？1人の子供が複数の本棚を持てる？
> > 1本棚=1子供です。1人の子供は複数の本棚持てないです。（本棚を新規作成はできるが、別の子供がいることになる）

>  本棚と子供を紐付けて複数管理したいのであれば、picbookのアカウント(親、これはユニークでなければならない)の
> 情報をマイページに表示するわけではない？読んだ絵本、ねんれいは誰の情報？最初に登録した子供？それともアカウント
> に紐づく冊数の合計？特にねんれいはだれ？(親のねんれいを表示したいわけではないと思うので笑)
> > これは、本棚を追加できる機能ができたら、変わります！本棚を追加できる機能ができたら、アカウントと本棚1:nに
> >  なるので、見せ方を変えますが、追加できる機能ができる前はアカウントと本棚が1:1なので、マイページに表示させる
> >  が良いと思ってます。年齢は敢えて子供と強調しないようにしてます。子供向けの利用想定ではあるのですが、
> >  初期絵本好きの大人にも使い勝手聞いてみようと思ってるので、本棚を所有する人の年齢を入力するイメージでした。

これだとすると`1親アカウント -> 複数子供アカウント -> 複数本棚`ということですかね？
初期は複数子供、本棚作る機能を作らないにしろ、firestore上のスキーマはこれを想定して整理し直したほうが良さそうです 🤔 

年齢などの情報は親アカウントに紐づくのではなく、子供アカウントが保持するという感じですね。
初回リリースは登録時に1子供アカウント1本棚が作成されて、どれぞれでデータ持つ　とかにしたほうが良さそうです

> 読んだ回数と本棚の登録は別の可能性がある？

これは了解です！違和感ないです！

**Comment by karokita** [comment]
@tokku5552 
そなんです。
子供が複数いるというのは徳田さんと私の間であったものの、アカウント生成の考え方について話せてなかったので、整理必要ですよね。年齢情報は子供アカウントが保持する感じです。初回リリース時は下記とても良いと思います！
>登録時に1子供アカウント1本棚が作成されて、どれぞれでデータ持つ

あとは、このタイミングで生年月日と名前を子供アカウント(≒本棚）に保持する、というのが厳しい場合は、一旦抜く対応して、追って検討でも良いのかなと思っておりました！

**Comment by tokku5552** [comment]
@Ta23ka98 
> そもそも、子供ごとの本棚/誰が読んだか/読んだ回数を管理するメリットがあまり無いように感じます🤔
(今後の機能追加に向けての実装だと思いますが...)

これは私は逆の意見で、今は子供が1人しかいませんが、2人いたら絶対に2人分は別で管理したいです。
こういうたぐいの機能は子育て系のアプリだと結構当たり前の機能だったりします。
私が使ってるアプリだと
- みてね
  - https://mitene.us/
  - 子供の写真を管理するアプリ。自動でフォトブックとか動画とか生成してくれる。フォトアルバムは各家庭に1冊ではなく、子供毎(なんなら成長過程で複数)になるはずです
- ぴよろぐ
  - https://www.piyolog.com/
  - 母子手帳とかに書いておくようなことをアプリで記録、夫婦で共有できるもの
  - ご飯食べたとか体温が何度だったとか、子供ごとに記録できないと困ります

子供を分けるという仕様の実装は特に難しくはないのかなと思います。親のアカウントに複数子供が紐づくというのが入るだけで、実装初期の今ならまだ影響も最小限ですみます。

> 子供Aが子供Bの本棚(の本)を読んでしまうことを、完全には防げない

これはそもそも別の論点というか、例えば親のYouTubeアカウントを子供が使えてしまうみたいなもので、pinでロックを掛けるとかもできますが、どちらかというと**自分の本棚に登録する**という行為自体に意味があると思うので、間違えたら取り消しできる機能だけつけてあげればあまり問題にはならないかなと思います。読んでないのに増やしても、それは体重管理アプリで痩せてないのに体重を-5kgで記録するみたいなものです。

**Comment by tokku5552** [comment]
@karokita 
> アカウント生成の考え方について話せてなかったので、整理必要ですよね

ですね！定例で話すと長くなりそうなので、どこかで会話したいですね 🤔

**Comment by karokita** [comment]
@tokku5552 

了解です！本件は明日話せたら明日、話せなかったら今週どっかで分科会開く、とかがよいですかね...🤔

>ですね！定例で話すと長くなりそうなので、どこかで会話したいですね 

進め方としては、issue79拝見した感じで一度徳田さんの方で整理していただく、でよいでしょうか？
https://github.com/pj-picbook/picbook/issues/79
何か私の方で要件整理した方がいいポイントなどあればお知らせください！
