### ISSUE TITLE
ユーザー退会機能

### ISSUE THREAD

**Issue by karokita** [pj-picbook/picbook#131]
## 概要

- ユーザー退会機能
- マイページ経由でユーザー退会できる機能

## 要件

- マイページ画面
  - アカウント情報の項目を追加
- アカウント画面
  - 登録しているメールアドレスを表示
  - アカウントを削除する をリンク表示
  - アカウントを削除する を押下するとポップアップが表示
- タイトル
  - アカウントを削除
- 本文
  - アカウントを削除するとログインできなくなります。アカウントを削除しますか？
- ボタン
  - キャンセル
  - 削除する

![スクリーンショット 2022-09-03 23 35 54](https://user-images.githubusercontent.com/96728192/188275349-41d4b391-ef55-424a-a49e-26995fa786e0.png)

**Comment by karokita** [comment]
@Ta23ka98 
ユーザー退会機能の内容を具体化してみました！
次の担当部分、こちらいかがでしょうか？

https://github.com/pj-picbook/picbook/issues/131

**Comment by Ta23ka98** [comment]
@karokita 
提案ありがとうございます🙇
了解です、やってみたいと思います🙌

**Comment by Ta23ka98** [comment]
@tokku5552 @karokita 
念の為こちらの要件についてですが...
・Authでアカウント削除
・Firestoreのデータも削除

ということで間違いないでしょうか？🤔

**Comment by tokku5552** [comment]
@Ta23ka98 
とりあえずはAuthのwithdrawだけ呼べば良いということになったかと思います！あくまでAppleの審査対策かと !

**Comment by Ta23ka98** [comment]
@tokku5552 

> とりあえずはAuthのwithdrawだけ呼べば良いということになったかと思います！

すみません。withdrawというメソッドがあるんでしょうか？🤔
調べ方が悪いのか、検索で出てきませんでした...
([delete()メソッド](https://firebase.flutter.dev/docs/auth/manage-users#delete-a-user)とは別なんでしょうか)

**Comment by tokku5552** [comment]
すみません、deleteメソッドであっています！

**Comment by karokita** [comment]
@tokku5552  @Ta23ka98 

先ほどのMTGをもとに、退会周りの画面フローをまとめてみたのですが、ログイン情報を入力する画面でアカウントを削除するボタンを作ると画面数増やさずに行けるかなと思ったのですが、どう思われますか？

![スクリーンショット 2022-09-09 0 10 05](https://user-images.githubusercontent.com/96728192/189159063-753718a3-b1c2-4b20-888e-19d82fde90c6.png)

あとMTGのメモ残しておきます。認識違うとこあったら、ぜひご指摘ください！

/MTG メモ
- re-authentication、認証済みでも、退会やパスワード変更などの重要な処理はもう一度認証させる必要があり（firebase authenticationの仕様上)
- アカウントページ、再認証ページ、アカウント削除ポップアップで同じ状態を管理し続ける必要あり（退会フォルダを組んでおいて、notifireで管理？）

**Comment by tokku5552** [comment]
因みにこのチケットではスコープ外としていると思いますが、firestoreのデータ削除はextensionsとかいうのを使うと簡単に実現出来そうでした。
https://firebase.google.com/products/extensions/firebase-delete-user-data

**Comment by karokita** [comment]
おお〜！たしかにパスワードのみの方がよさそうですね！

今日はパソコン閉じたので、明日反映したいと思います🙋‍♀️

**Comment by Ta23ka98** [comment]
@karokita 
自分も違和感ないです！👍
パスワードのみのデザインの方で実装やってみます

@tokku5552 
re-authentication＆拡張機能へのリンクありがとうございます🙇

**Comment by karokita** [comment]
@Ta23ka98 

はい！よろしくお願いします！
微妙に文言を変えたので、こちらでご対応いただければと思います。

![スクリーンショット 2022-09-09 22 46 43](https://user-images.githubusercontent.com/96728192/189365063-1b038f9c-648e-4c3c-90b5-29ebb2c957aa.png)

**Comment by Ta23ka98** [comment]
@tokku5552 
↑のスクショの右側のページ(ReAuthPage)について、アカウント削除後にsnackBarを表示する方法をアドバイス頂きたいです🙇
(再認証とユーザ削除機能の実装自体は完了)

ログイン・会員登録画面と同じく、再認証・ユーザ削除のエラー時はsnackbarを表示するようにしています。
ただユーザ削除後は未ログイン画面(FirstPage)に遷移してしまい、その未ログイン画面でsnackBarを表示する方法に悩んでいます🤔

**Comment by Ta23ka98** [comment]
@tokku5552 
こちらAsyncValueを使えば実装できそうなので、ちょっとやってみます🙌
