### ISSUE TITLE
読書スタンプ

### ISSUE THREAD

**Issue by karokita** [pj-picbook/picbook#137]
## 概要

絵本を読むとスタンプがつく
→読書の可視化でモチベーション喚起

## 詳細

![スクリーンショット 2022-09-07 22 03 48](https://user-images.githubusercontent.com/96728192/188886569-aa007e6c-7cc7-46ca-8eb3-4478e8eeb429.png)

## 要件

■スタンプ画面
◎機能
・BookのregisteredDateTime: DateTimeをベースに集計
・該当の日にちに、書籍登録された場合は、色がつく
・使うウィジェット案（flutter_calendar_carousel/Circular style/Custom Icon Events)https://pub.dev/packages/flutter_calendar_carousel

◎画面上での表示
(絵本を読んだ日)
・icon：sentiment_very_satisfied 
・color：Colors.deepOrange.shade700,

(絵本を読んでない日)
・color：Colors.grey.shade100

■ボトムナビ
・icon_approval_rounded

## 備考
初期からは外す
・選択するとその日に読んだ本が出てくる
・読んだ冊数によって、アイコンの色とアイコンが変更
（アイコン候補：sentiment_very_satisfied 、sentiment_very_satisfied_outlined、sentiment_very_satisfied_sharp、sentiment_satisfied_alt_rounded、sentiment_satisfied）
・本当は登録ボタンとは別途で読んだボタンがあると良いが、一旦考えない

## 参考
・Flutter製の個人開発アプリ「禁欲スカイウォーカー」の技術的まとめ　https://zenn.dev/tetsufe/articles/ce999e95c9c2d7e14e54
・カレンダー上でのアイコン表示いめーじ　https://stackoverflow.com/questions/62838913/flutter-calendar-showing-custom-data-on-days-not-works-well

**Comment by Romu1273x** [comment]
@karokita 

> ・BookのregisteredDateTime: DateTimeをベースに集計

上記ではなく、bookshelfHistories.dateの方が良さそうに見えますが、問題ないでしょうか？
もし、何か意図があれば教えてください。

**Comment by Romu1273x** [comment]
@karokita 
あ、やっぱり大丈夫です。
現状bookshelfHistoriesが使われていないんでしたね。
