### ISSUE TITLE
カテゴリ機能

### ISSUE THREAD

**Issue by karokita** [pj-picbook/picbook#138]
## 概要
・検索画面にカテゴリ機能を設ける
・絵本との出会いを創出するため

![スクリーンショット 2022-09-07 22 16 41](https://user-images.githubusercontent.com/96728192/188887980-c75b00b9-0ed1-488f-9141-96410e0ded1d.png)

## 要件
・検索画面にカテゴリを表示
・カテゴリを押下するとカテゴリごとの書籍が表示
・初期のカテゴリは6カテゴリ(にんきのえほん/どうぶつ/のりもの/たべもの/からだ/いきもの・しょくぶつ)
※タグ数が増えてきたら、分類する

## 備考
・本来は読みたいボタン/読みたいリストがあると良いが、いったんなし
・絵本の登録ボタンは省くかどうかも検討
・初期はベタで画面作ってくのも検討

**Comment by karokita** [comment]
@tokku5552 @kawadon780 

少し詰まってる部分があり、ご質問させてください！

現在、該当のカテゴリを押すと、カテゴリに関連したキーワードで絞り込みをかけた結果画面が表示されるところまできました。(ブランチ：https://github.com/pj-picbook/picbook/tree/feature/%23138_category）
![スクリーンショット 2022-09-11 16 31 34](https://user-images.githubusercontent.com/96728192/189517805-e36ccb71-8b17-4f5d-8d88-b94118991e90.png)

ただ、ここからが詰まってます！
1つのカテゴリごとに、複数条件でキーワードを指定して、絞り込みできるようにしたいのですが、普通にキーワードを羅列してしまうとAND条件になってしまいます。
（ex.「のりもの」カテゴリの場合、「車」かつ「電車」の結果が返ってくる）

こちらOR条件で記述する方法などご存じでしょうか...？
（ex.「のりもの」カテゴリの場合、「車」もしくは「電車」で結果が返ってくる）

(AND条件になってしまう現在の書き方）
![スクリーンショット 2022-09-11 16 57 33](https://user-images.githubusercontent.com/96728192/189517734-e9028b14-b150-46cb-a513-3215c83dba1d.png)

**Comment by tokku5552** [comment]
仕様を見るとorFlagというパラメータを1にしてやるとOR検索になるようですね
https://webservice.rakuten.co.jp/documentation/books-total-search

**Comment by karokita** [comment]
@tokku5552 
おぉ、API自体の仕様も関係してくるんですね。
みてみたいと思います。ありがとうございます！
