### ISSUE TITLE
本棚から書籍を削除(UI)

### ISSUE THREAD

**Issue by karokita** [pj-picbook/picbook#139]
## 概要

- 本棚画面で、書影を長押しすると本棚から削除ができる機能

## 要件

- 本棚で絵本を長押しするとポップアップで削除確認画面が表示
  - 本文
    - 絵本を本棚から削除しますか？
  - ボタン
    - はい
      - 書籍を本棚から削除
      - 削除後にsnackbarでテキスト表示
        - 本棚から絵本を削除しました。
    - いいえ
      - 前画面に戻る

**Comment by karokita** [comment]
@どなたかおやさしい方
本棚から書籍を削除するタスクに手をつけたいと思ってまして、アドバイスいただけるとうれしみです！

現状の書籍登録の処理を参考にしながら削除を実装しようと思ったのですが、
下記の考え方であってますでしょうか？


**<やろうとしていること>**
・作品詳細ページで削除ボタンを押下すると本棚から削除される
(※一旦、長押し削除はやめてボタン削除にする）

**<現状のpicbookでの書籍登録の際の処理>**
・book_detail_pageで登録ボタンを押すと、book_notifire.dartのregisterBookの処理が走る
・book_notifire.dartのregisterBookでは、bookshelfRepositoryのuidをfetchしつつ、booksRepositoryをcreateしている

**<上記を踏まえた上での書籍削除の手順>**
・book_notifire.dartでdeleteBookを作成する
・bookを引数に設定して、book idを渡す
・book_detail_page.dartでボタン押下時に、notifire.dartで設定したdeleteBookを呼び出すことで削除完了

**Comment by Romu1273x** [comment]
あってます。
books_repositoryにdeleteメソッド（firebaseのデータを削除）がないのでそこからですね。
user_repositoryにdeleteメソッドはあるのでそれ参考にすれば良いと思います。

**Comment by karokita** [comment]
Romuさん、ありがとうございます！やってみます！

**Comment by karokita** [comment]
どなたかご存知の方いたら教えていただけるとありがたいです🙇‍♀️
今、本棚から書籍を削除しようとしていまして、またまたひっかかっています。

現在、user_repositoryを参考にしながら、books_repositoryでdeleteメソッドを作ろうとしています。

が！user_repositoryは削除するドキュメントの名前が「user.id」と明確にあるのですが、books_repositoryだと空欄になっていて、何を指定したら…？となってます。(添付画像）

これは何かまた別の場所でidを定義したらいいのか、もしくは空欄のままで良いものでしょうか？
![スクリーンショット 2022-09-12 21 49 41](https://user-images.githubusercontent.com/96728192/189660003-b1139659-8791-4a64-8a45-9b992ad8a4bf.png)

**Comment by kawadon780** [comment]
@karokita 
空欄で現状は問題ない認識です。

理由としては、空白の場合、ランダムで存在しないユニークな文字列が生成されているはずです。勿論ここのIDは自分で好きな値を設定できますが、それをする意味は現状の仕組みだとないような気がします。

user_repositoryのuidは「firebase auth」により生成されたIDを「firestore」に保存しているので、設定している感じです。

**Comment by kawadon780** [comment]
@karokita 
ってcreateの方みてましたが、deleteの方は指定しないとだめでした。

**Comment by kawadon780** [comment]
@karokita　五月雨ですみません。
bookにID保存していると思ったんですが現状ないので保存する場所と、保存する処理を書かないといけなそうです。

**Comment by karokita** [comment]
@kawadon780 今めちゃめちゃ探してましたw
教えていただいてありがとうございます！

そしたらUserかbookshelfでID保存している見本を探して、bookのIDの保存場所を作る&保存処理を書くと良さそうですね。

アーキテクチャを見ている感じですとxxxxrepository.dartでその処理を行なってる感じでしょうか？🤔

**Comment by kawadon780** [comment]
@karokita 
自分でここら辺コード書いてて実装完全にわすれていました（泣）

んで、参考になるはずのコードなのですが
`      bookshelfId: bookshelfs[0].id, // TODO:本来は複数予定`
の所みるとこんな風に「 bookshelf」クラスにfeachAllで取得した0番目（本棚一個想定なので）のIDを設定しているとスーパーゴリラ押しなのでこれを真似てしまうとちょっとまずそうですね。。本は複数ですもんね。


なので、本を登録した時に本の情報を取得する処理を書いて（ _bookshelfRepository.fetchAllみたいな）、IDを取得したら再度本のIDを更新する処理を書かないといけなそうなです。
で、IDを保存する場所ないので
`Bookshelf({
    @Default("") @JsonKey(name: 'id') String id,`
を真似してBookクラスあたりにidを追加すればよさそうです。

BookクラスはFreezedで更新しないとだめです～。
