### ISSUE TITLE
本棚から書籍を削除(機能) 

### ISSUE THREAD

**Issue by karokita** [pj-picbook/picbook#144]
## 概要

・本棚から書籍を削除する機能の実装

## 要件

・bookのID保存
・作品詳細画面で「削除する」ボタン押下時に、削除

<img width="223" alt="スクリーンショット 2022-09-12 23 18 57" src="https://user-images.githubusercontent.com/96728192/189677984-cb5316a7-f9a8-4253-a561-185903bbfc25.png">

##関連issue

#139

**Comment by kawadon780** [comment]
本にIDをセットする処理がないので追加予定。
冗長すぎてやばいけど、とりあえず本のidを全更新を登録時に毎回書く予定。
いずれfunctionによってそこら辺いい感じにできるなら変更したい。

**Comment by kawadon780** [comment]
`冗長すぎてやばいけど、とりあえず本のidを全更新を登録時に毎回書く予定。`
ISBNをdocIDに使うので考慮しなくよくなった。
