### ISSUE TITLE
プラポリ&利用規約

### ISSUE THREAD

**Issue by tokku5552** [pj-picbook/picbook#15]
## 概要

- プライバシーポリシーページと利用規約ページをWebで用意し、アプリ上からWebViewで表示できるようにする

## 詳細

- 例：ログイン画面を実装する。
- デザインは仮のものでOK
- 画面遷移

## 要件

- 利用規約の内容の書き方
-  利用規約　
  - https://corporate.vbest.jp/columns/4551/#:~:text=%E3%80%8C%E5%88%A9%E7%94%A8%E8%A6%8F%E7%B4%84%E3%80%8D%E3%81%A8%E3%81%AF%E3%80%81,%E9%81%B8%E6%8A%9E%E3%81%99%E3%82%8B%E3%81%A8%E3%81%84%E3%81%86%E3%82%82%E3%81%AE%E3%81%A7%E3%81%99%E3%80%82
- 利用規約の同意の取り方
  - https://wandk-law.com/column1161/
-  利用規約雛形
  - https://topcourt-law.com/terms_of_service/user_policy
- プライバシーポリシー
  - https://kiyaku.jp/hinagata/privacy.html

- 利用規約の実装事例
  - notionで作ってる事例
    - https://onecomme.notion.site/ba1a58fe171241868e27b61c4411dda7
  - muuteの利用規約
    - https://muute.jp/rule

## 期限

- 例：2020/08/01

## タスク一覧

ここに本ストーリーに紐付くタスク番号を列挙する

**Comment by karokita** [comment]
- github pagesで作ってみた
  - https://docs.github.com/ja/pages/getting-started-with-github-pages/creating-a-github-pages-site
  - https://zenn.dev/takuho/articles/99b9f625afbb87
  - （便利&かなり自由効くのでLPもありかも）

 - 内容
   - メアド、アプリ名が必要なので要アップデート
   - 内容もう少し時間をおいて考える

 - URL
   - https://pj-picbook.github.io/picdoc/docs/privacypolicy.html
   - https://pj-picbook.github.io/picdoc/docs/terms.html

※privacypolicyのみ作成
