### ISSUE TITLE
読んだボタンと本棚登録ボタンの処理

### ISSUE THREAD

**Issue by karokita** [pj-picbook/picbook#177]
## 概要
読んだボタンと本棚登録ボタンの挙動を整理する

## 要件

**（初回に登録する書籍）本棚に登録→読んだ履歴にも登録**
　※本棚登録ボタンを押したタイミングで複数処理が走る
　└bookshelfsのbooksにデータが入る
　└ bookshelfHistoriesにデータが入る
　　　　bookshelfHistories.dateをもとにスタンプが押される

**（二回目以降に読んだ登録する書籍）読んだ履歴に登録、本棚には登録されない**
　※読んだボタンを押すと読んだ履歴に登録される
　└ bookshelfHistoriesにデータが入る
　　　　bookshelfHistories.dateをもとにスタンプが押される

**(一度も本棚登録していない場合）本棚に登録していないと読んだ登録できない**
　※本棚登録してない状態で読んだボタンを押すとエラーが出る
　└本棚に登録してください、とエラーが出る。

## 関連ストーリー

https://github.com/pj-picbook/picbook/issues/154#issuecomment-1275408033

**Comment by Romu1273x** [comment]
リファクタを以下で行う
・#194
