### ISSUE TITLE
main/developブランチの保護

### ISSUE THREAD

**Issue by tokku5552** [pj-picbook/picbook#18]
## 概要

- 開発に入る前にmain/developブランチを保護しておく

## 要件

- 例：メールアドレスはログインしているユーザのメールアドレスを表示する
- 下記のイメージ図を参考にしてください。

- デザインは別途まとめて対応するので、Flutter 標準Widgetを使って簡易的な実装にとどめてください。
- 要件以外の要件をどうするかは、エンジニアにお任せします。迷ったら相談してください。

## 期限

- 例：2020/08/01

## 親ストーリー

ここに親ストーリーのissue番号を記載する

**Comment by tokku5552** [comment]
おそらくリポジトリのownerしかできないので @karokita をアサイン済み

**Comment by karokita** [comment]
@tokku5552 
下記対応しました！

- デフォルトのブランチをdevelopに変更
- ブランチの保護設定（画像赤枠)


ブランチの保護設定については、いったん画像赤枠部分のみ（Require a pull request before merging/Require approvals)にしたのですが、他に入れておきたい項目があればお知らせください。


![スクリーンショット 2022-07-21 20 55 51](https://user-images.githubusercontent.com/96728192/180208295-a7b0d1ef-9a03-474f-b290-2baff078d22f.png)

![スクリーンショット 2022-07-21 20 56 48](https://user-images.githubusercontent.com/96728192/180208183-59b0f5f0-c094-4d19-96d7-f3550e9d693d.png)

**Comment by tokku5552** [comment]
@karokita 
ありがとうございます！問題なさそうなのでクローズします！
