### ISSUE TITLE
ISSUEテンプレートの改善

### ISSUE THREAD

**Issue by tokku5552** [pj-picbook/picbook#20]
## 概要

- ISSUEテンプレートは他からそのまま流用してきたものなので、今回用に項目など見直す

## 要件

- 例：メールアドレスはログインしているユーザのメールアドレスを表示する
- 下記のイメージ図を参考にしてください。

- デザインは別途まとめて対応するので、Flutter 標準Widgetを使って簡易的な実装にとどめてください。
- 要件以外の要件をどうするかは、エンジニアにお任せします。迷ったら相談してください。

## 期限

- 例：2020/08/01

## 親ストーリー

ここに親ストーリーのissue番号を記載する

**Comment by karokita** [comment]
要件列挙に特に現状のテンプレート支障なさそうだと思いました！
なので、closeします。

**Comment by pj-picbook** [comment]
@tokku5552 

そうですね、
現状だとベストなテンプレートまだ見えないなというのが正直なところです！

今どんな書き方がいいかな、と試してまして
ex.
親タスク：https://github.com/pj-picbook/picbook/issues/12
子タスク：https://github.com/pj-picbook/picbook/issues/27

どの粒度で要件まとめるとよいか、
どの粒度で子タスク切ったらよいか、
などちょっとまだベストな感じには辿り着いてないです。

なので、一度現状で1週間運用してみて、もっとここ詳細に書いてほしい、
的なところを定例でヒアリングして項目固めていく形でいかがでしょうか？

期限はmilestone機能がまだ使いこなせてないので、一旦入れる
代用がききそうだったらとる、的な感じで行ければと思ってます！

**Comment by tokku5552** [comment]
@karokita 
承知しました！  
やり方が定まってきたタイミングで実施するという感じですかね？  
それであればオープンしておいてpendingにしちゃってもいいかなと思いました！

**Comment by karokita** [comment]
@tokku5552 
はい、こちらのイメージです！
＞やり方が定まってきたタイミングで実施するという感じですかね？

徳田さんにいただいた形の進行がよさそうとおもいましたので、
ReopenしてPendingにしました。
