### ISSUE TITLE
riverpod + freezed + state_notifier入れる

### ISSUE THREAD

**Issue by tokku5552** [pj-picbook/picbook#23]
## 概要

- 開発に入る前に「[salon_app_doc の README.md](https://github.com/kboy-salon/salon_app_doc)」 を読んでください。
- 例：ログインボタンを実装

## 要件

- 例：メールアドレスはログインしているユーザのメールアドレスを表示する
- 下記のイメージ図を参考にしてください。

- デザインは別途まとめて対応するので、Flutter 標準Widgetを使って簡易的な実装にとどめてください。
- 要件以外の要件をどうするかは、エンジニアにお任せします。迷ったら相談してください。

## 期限

- 例：2020/08/01

## 親ストーリー

ここに親ストーリーのissue番号を記載する

**Comment by tokku5552** [comment]
@karokita 
テストも兼ねて投稿しますが、riverpodはhooks_riverpodで大丈夫ですかね？

**Comment by tokku5552** [comment]
issueへのコメントテスト

**Comment by karokita** [comment]
@tokku5552 
見逃していたのですが、riverpodはhooks_riverpodで大丈夫です！

@IshitaniKatuya @kawadon780 @hironobu-kkk @Romu1273x @Ta23ka98 
問題ないとは思うのですが、共有のためメンションつけておきます。
