### ISSUE TITLE
BottomNavigator作る

### ISSUE THREAD

**Issue by tokku5552** [pj-picbook/picbook#24]
## 概要

- 開発に入る前に「[picbook の README.md](https://github.com/pj-picbook/picbook#readme)」 を読んでください。

## 要件

- 画面遷移しても永続するBottomNavigationBarを作成
- 非表示画面：スプラッシュ、未ログイン時画面、ログイン、新規登録画面、バーコードスキャン画面
- 表示画面：本棚、マイページ、検索画面、作品詳細画面
- 要素と遷移先　
  - ①絵本の棚
    - Icon：Icons.auto_stories 
    - label：絵本の棚 
    - 遷移先：本棚ページ
  - ②マイページ
    - Icon：Icons.person 
    - label：マイページ 
    - 遷移先：マイページ

## 期限

- 例：2020/07/26

## 親ストーリー

- なし

## 備考

- 私は着手&再現できていないのですが、ダイゴさんの書いたこちらの記事が参考になりそうな予感です
https://zenn.dev/mamushi/articles/nested_bottom_nav

**Comment by karokita** [comment]
@Romu1273x 
BottomNavigatorの要件をまとめました。
ご不明点あればお願いします！

**Comment by Romu1273x** [comment]
参考記事はHookWidget使ってますが、こちらの方が都合が良かったりしますでしょうか？
StatefulWidgetで実装しようと思っていたのですが、HookWidgetの方がメリットあったりしますか？

**Comment by karokita** [comment]
@Romu1273x 
こういうやり方もあるよ、という例として貼ったので、
StatefulWidgetでの実装で全く問題ないです！

**Comment by Romu1273x** [comment]
了解しました。
せっかくなので、記事参考にStatefulWidgetに置き換えたものを作ろうと思ってます。

**Comment by Romu1273x** [comment]
現状の報告だけしておきます。

記事のやり方でやってみようと思い、enumを作成したのですが、そこでエラー出てしまって解決方法を調べ中です。
あまりハマるようだったら以前自分が実装してたやり方にシフトしたいと思います。
![スクリーンショット 2022-07-22 8 25 57](https://user-images.githubusercontent.com/74139918/180331230-6822095a-8670-4baa-b799-ee5440124bdc.png)

**Comment by Romu1273x** [comment]
9行目と15行目が　, → ;　でした笑

**Comment by Romu1273x** [comment]
Pull request 送りました。
Pull requestという行為は初めてやるので不備あったら教えてください。
