### ISSUE TITLE
バーコードスキャンする

### ISSUE THREAD

**Issue by karokita** [pj-picbook/picbook#25]
## 概要

- 絵本についているバーコードを読み込めるようにする

## 要件

- flutter下記Packageを利用して、絵本のISBNコードを読み込む
https://pub.dev/packages/flutter_barcode_scanner
https://pub.dev/packages/barcode_scan

設定方法
https://www.youtube.com/watch?v=YIvOdkdzD70

調べてみたところ画面作成が必要&SDKの設定が必要なことがみえてきまして、pubspec.ymlのimportのみではタスクが完了しなさそうなことがわかってきました。  
[Scanning QR-Codes or Barcodes with Flutter (mobile_scanner)](https://www.youtube.com/watch?v=YIvOdkdzD70)

## 期限

- 2020/07/26

## 親ストーリー

#14

**Comment by hironobu-kkk** [comment]
push してみたのですが、featureでつくれてないぽいですので、ちょっと見返して作り直します。
プルリクは出さないです。
いろいろ読み込んでます。

**Comment by karokita** [comment]
@hironobu-kkk 

一旦こちらで手順FIXしたのでよろしければ参考にしていただければと思います！
https://docs.google.com/document/d/1tJfYOjiOzbCPVax5cRr-Ml6iCYlGOqAALegR27I8250/edit?usp=sharing

あとはあした土曜日の12:00-18:00は作業予定でずっとPC前にいるので
もし手こずってひろのぶさんのご予定空いてたら、お声かけください（zoomしながら設定してみるとかありかもとおもいました🙌）

**Comment by hironobu-kkk** [comment]
承知しました！ありがとうございます！

**Comment by hironobu-kkk** [comment]
https://github.com/AmolGangadhare/flutter_barcode_scanner/issues/288

flutter_barcode_scanner ^2.0.0 is forbidden　という記述がありましたので、他のパッケージも探してみようと思っています。

**Comment by karokita** [comment]
過去ログを転載

slack上でのやりとり
https://flutteruniv.slack.com/archives/C03PARB9W1F/p1658582546995539

議事録
>バーコードスキャンのパッケージにつき、mobile_scanner のほうが良さそうです。（flutter_barcode_scanner ^2.0.0 is forbidden）上記パッケージがpubspec.yaml に記載してpub get　するのみで使える様子（https://pub.dev/packages/mobile_scanner/install）
ですので、pubspec.yaml に記載してコミットしてプッシュ済みです。
UI完成後、ボタン押したらスキャン画面が起動するように設定するイメージ

**Comment by kawadon780** [comment]
[mobile_scanner ](https://pub.dev/packages/flutter_barcode_scanner
https://pub.dev/packages/barcode_scan)
どっちつかおうか確認。

**Comment by kawadon780** [comment]
https://pub.dev/packages/barcode_scan
の方は「DISCONTINUED」なので怪しいので
flutter_barcode_scanner 
を使う。

**Comment by kawadon780** [comment]
とりあえずデザインはこんなもんで。
バーコードは何でも対応できるものは読み込んで、成功したら検索結果に。
<img src= https://user-images.githubusercontent.com/54085013/183703756-ee439be8-df53-4f27-85ea-dbafdd8846bf.png height =600 width=300>
