### ISSUE TITLE
検索画面のUI作成

### ISSUE THREAD

**Issue by karokita** [pj-picbook/picbook#27]
## 概要

<img width="185" alt="スクリーンショット 2022-07-16 22 31 56" src="https://user-images.githubusercontent.com/69064290/179357066-7f15edbe-ecdc-43d5-b82b-5ca37b8556f4.png">

## 詳細

- 楽天書籍検索APIを利用して、検索を行うページの画面UI

## 要件

- **検索画面のUIを作成する**
  - **要素①：検索窓で文字入力とバーコードスキャン画面での遷移をできるようにする**
    - 表示要素
      - 検索窓
      - hint text ：絵本を探す
      - アイコン：Icons.qr_code
        - 遷移先：バーコードスキャン画面へ遷移
  - **要素②：リストで検索結果の一覧を表示**
    - 表示要素
        - 書籍リスト
        - 書籍画像（書影）
        - 書籍タイトル
        - 著者名
        - 本棚登録アイコン
    - 遷移先
      - 書籍情報
        - 押下で作品詳細ページへ遷移
      - 本棚登録アイコン
        - 押下で本棚に登録
        - ※遷移させるorポップアップを出すなどの挙動は要検討

  

## 期限

- 2020/07/26

## 親ストーリー

#12

**Comment by kawadon780** [comment]
@karokita @tokku5552 
すみません、初歩的な質問になります。
本棚登録はFireStoreへの登録のみでローカルに保存はしないで認識で大丈夫でしょうか？
その場合、オフラインであれば本棚の情報は白紙表示など問題ないでしょうか？

**Comment by tokku5552** [comment]
@kawadon780 
> 本棚登録はFireStoreへの登録のみでローカルに保存はしないで認識

一旦それで行こうということになったかと思います！

> オフラインの場合白紙表示やオフラインの場合使えない旨のダイアログ表示

そもそもログイン処理を挟むので、ここまでの考慮は初期スコープから外して良いかなと思います。
@karokita いかがでしょうか？

少なくとも検索画面UIのタスクとは関係ないので、別にissue立てて議論したいですね 🤔

**Comment by karokita** [comment]
@kawadon780 @tokku5552 

確かにアプリでそもそもどう対応するかという話にもなるので、別issue立てて話したいですね。
一旦、初期からは外すで良さそうだなと思いました！

**Comment by kawadon780** [comment]
@kawadon780 @tokku5552 
ご返答ありがとうございます。

> 一旦それで行こうということになったかと思います！
承知しました

別isuue承知しました。
通信系のstatuscodeが200以外に関しては各自適当にーとかざっとな指標でもいいので指示いただければ幸いです。よろしくお願いしますm(_ _)m

**Comment by karokita** [comment]
@kawadon780 

かわどさん、ステータスコードこちらでよかったでしょうか。
https://www.itmanage.co.jp/column/http-www-request-response-statuscode/#anc003
（もし全く違ったらすみません！）

特にこれというものを今持っているわけではないので、
かわどさんの方で今回はこれがよさそうだぞ、という叩きをつくっていただいて
そちらを持ってすり合わせながら、実装いただくというような進め方はいかがでしょうか？

ご確認よろしくおねがいします！

**Comment by kawadon780** [comment]
@karokita 
確認いただきありがとうございます。

はい、まさにそれです。

> かわどさんの方で今回はこれがよさそうだぞ、という叩きをつくっていただいて
そちらを持ってすり合わせながら、実装いただくというような進め方はいかがでしょうか

進め方問題ないです。

下記Isuueの方に記載していきますー。
https://github.com/pj-picbook/picbook/issues/53

**Comment by karokita** [comment]
@kawadon780
おお、よかったです。
記載&進行よろしくおねがいします！

**Comment by tokku5552** [comment]
@karokita 
ちょっと確認ですが、このissueのクローズはfirebase/外部APIは実装せず、ダミーデータなどでUIのみ作成する　ということであってますか？ API実装のタスクを立てれていないのと、APIのエラーハンドリング、端末のエラーハンドリングは別の話なのでそれぞれのissueで会話するのが良いかと思います。一箇所にまとめておかないとあとから追えなくなるので。

**Comment by karokita** [comment]
@tokku5552 

はい、確認いただきありがとうございます！

検索でたてたストーリーのissue https://github.com/pj-picbook/picbook/issues/12 を見ていただくと　
下記のように書いてまして、元々は下記のように分割してタスク分解する予定でいました！

  - ①検索画面のUIを作成する
  - ②楽天書籍検索APIで書籍を検索できるようにする
  - APIのURL
  - https://webservice.rakuten.co.jp/documentation/books-book-search
  - Application ID
  - e06e2a5afcf14b52139c1fb6c58e9dbc
  - ③検索前画面で表示されるリストの書籍内容を絵本に絞る
  - ④検索結果で出たリストを本棚に入れる

ただ、こちらのissueのコメント欄で、かわどさんAPIに関する記載をまずしていただいていたので、
こちらでUI作成/APIを進行する流れ、と認識を変えまして、途中からその前提で進行しています。
（元々粒度は各人に任せて、後から検討しようとなっていたので）

で、これからどうするかについてです！
・これは運用の決めだと思うのですが、今後はUIとAPI実装を分けてissue運用していくことに決めてく感じでいきましょうか？
・また、その場合は本issueをAPI連携に変更して、画面作成を別途issue立てる対応すると議論も残って良いかなと思いましたがいかがでしょう？

**Comment by tokku5552** [comment]
> こちらでUI作成/APIを進行する流れ、と認識を変えまして、途中からその前提で進行しています

だとすると一旦ストーリーのタスク整理と実施順序を変えていただいて、APIのissueで実装するのが良いかなと思います。まだこのissueでAPIに関する議論は始まっていない認識なので 👀

**Comment by tokku5552** [comment]
詳細な議論は各issueで行えればと思いますが、なんか噛み合っていない気がするので一応場合分けをしておくと
- デバイスがオフラインの場合
  - そもそもfirebaseと通信できない(not API)。ログイン状態を正常に保持できないのでアプリとしての動作保証をしない(少なくともver 1.0では) #53 (タイトル的にはそれ以外も含んでいる？)
  - ダイアログ出して警告出すとかがベターだが、1.0.0リリースまでの実装機能からは外す。なくても大枠は動くので
- デバイスがオンラインの場合(上記の話とは別) 
  - 楽天APIが200を返す場合
    - 正常な処理 #57 
  - 楽天APIが200以外を返す場合
    - API呼び出しの前後でネットワークが不安定だったり、楽天APIが落ちていたりいろんな状況が考えられるが今回考慮が必要 #57

**Comment by tokku5552** [comment]
ちなみに今もうfeature/#27_hoge でAPI実装の作業やっちゃってるよ！　ということであればブランチ名を変えれば解決します。
 ```bash:
# #27のブランチにした状態で
git branch -m <新しいブランチ名>
```

**Comment by kawadon780** [comment]
すみません、そもそもUIだけ作るIsuueだったのでapi気にしなくてよかったですね、、、
完全に余計な質問をしてしまいました、申し訳ないですorz

**Comment by karokita** [comment]
@kawadon780 

いまってそんなにコミュニケーションルールきちんと決めてたわけじゃない&一回やってみてこれからみんなでルール決めてこうというタイミングなので、かわどさんがあやまる必要全然ないなと思いました！

issueごとのディスカッションの仕方を考える良い機会になったと思います。
既にトピック盛りだくさんですが、本件も夜の定例ではなしたいです！

**Comment by kawadon780** [comment]
@karokita 
そう言っていただけると幸いです。

あとは本日の定例で確認したいと思います。色々ありがとうございますm(_ _)m

**Comment by kawadon780** [comment]
とりあえず、RiverPodとかmvvmとか意識してない実装で簡単なのはできました。
楽天apiにキーワードだけ指定してるんですが、それだと絵本以外もでてますね。api周りの話は別のIssueで致します。

https://user-images.githubusercontent.com/54085013/181581477-4dadadd2-070c-44f8-b68b-b82bd8fa49b2.mp4

**Comment by kawadon780** [comment]
@karokita
絵本とかの画像なんですが、ネットワークを通して取得する時に、通信の状況次第で結構時間がかかります。
その間に表示するものと画像がない場合の画像や表現を決めてほしいなーとか思うんですがいかがでしょうか？

**Comment by karokita** [comment]
@kawadon780 

おお、たしかに通信状況考慮したほうがよいですね。

スケルトンスクリーンでご対応いただく形でお願いできますでしょうか？
イメージとしてはこんな感じです↓
https://zenn.dev/seya/articles/4a0e69655c3a17

もし厳しい場合は、お知らせください！
