### ISSUE TITLE
本棚画面のUI作成

### ISSUE THREAD

**Issue by karokita** [pj-picbook/picbook#28]
## 概要

- 本棚の表示機能を作成する
![スクリーンショット 2022-07-19 22 19 22](https://user-images.githubusercontent.com/69064290/179759992-f807c049-5a8b-441a-93ea-1535eeaf805d.png)

## 詳細

登録済みの絵本を表示する画面

## 要件
- app bar 
  - title：絵本の棚
- 書籍一覧
  - 表示
    - flutter_staggered_grid_viewで絵本のサイズに合わせて表示する
      - https://pub.dev/packages/flutter_staggered_grid_view
  - 遷移
    - 絵本の画像をクリックすると作品詳細ページへ遷移
- floating action button
    - 遷移 
    - 押下で検索画面へ遷移

## 期限

- 2020/07/26

## 親ストーリー

#10

**Comment by IshitaniKatuya** [comment]
floating action buttonここで作成しますか？
ベースとなる画面の
Scaffoldのbody部分をBottomNavigationVarで切り替えていくのかなー
と思っていたので、同様に表示非表示の切り替えを行うのかなと

**Comment by pj-picbook** [comment]
@IshitaniKatuya 
おお。そんなことができるのですね！
floating action buttonは本棚画面のみ表示させるイメージだったので、一緒に作っちゃうのがよいかな？と思ってました。
（というかそれ以外の方法が浮かんでなかった感じですw）

一旦、Bottom Navigation担当のRomuさんの回答を待って、
作成場所どこにするか決められたらと思いました！
（なので、floating action button以外のところから着手いただけるとありがたいです）

@Romu1273x 
実装の際に下記でいく場合は、floating action buttonの表示非表示も 【#24 BottomNavigator作る】に組み込めればと思うのですが、いかがでしょうか？
>Scaffoldのbody部分をBottomNavigationVarで切り替えていく

**Comment by IshitaniKatuya** [comment]
こちらでも全然対応可能なので、Romuさん含めて検討いただければありがたいです！

**Comment by Romu1273x** [comment]
BottomNavigationBar部分以外は各画面のWidgetを上に重ねて表示する作りになります。
floating action buttonについては必要な画面（本棚画面）で実装するのがでやる方が妥当だと思います。
共通画面でやるとなるといちいち画面を判断して出す出さないの判定がいるので。

**Comment by IshitaniKatuya** [comment]
Stack利用であれば妥当ですね！
余計な事いって申し訳ありませんでした、、、
上記内容で実装進めます!

**Comment by karokita** [comment]
@IshitaniKatuya  @Romu1273x 
ポンデさん、Romuさんご確認ありがとうございます。
ではでは、floating action buttonは本棚画面で実装いただく形で、よろしくおねがいします！

**Comment by Romu1273x** [comment]
@IshitaniKatuya
すみません、よろしくお願いします。

**Comment by IshitaniKatuya** [comment]
絵本詳細や検索画面への遷移は他の画面が実装されないと実現できないので
TODO的な記載をしておいて、ダミーのContainer表示するとかで大丈夫ですか？

**Comment by IshitaniKatuya** [comment]
あと、本棚表示する内容に関しても
ダミーデータを準備して進めようかと思っています。
あくまでUIの実装で、
どのデータをどこに表示する等は別タスクで切られる認識であっていますか？

**Comment by karokita** [comment]
@IshitaniKatuya 
本棚の子タスクきりました！ただ、着手できるのが楽天書籍検索APIと登録機能が実装されたあとになるかなと思いましたので少し順番としては後の方になってくるかなと思いました。
#47 

ので、作品詳細画面のUIをまとめましたので、本棚画面のUIが終わりましたら、こちらを先に着手いただけるとありがたいです！
#48
