### ISSUE TITLE
マイページ - 画面作成

### ISSUE THREAD

**Issue by tokku5552** [pj-picbook/picbook#29]
## 概要

- 画面を作成する
- 必要に応じて予めentityまで作る

## 要件

- 例：メールアドレスはログインしているユーザのメールアドレスを表示する
- 下記のイメージ図を参考にしてください。

- デザインは別途まとめて対応するので、Flutter 標準Widgetを使って簡易的な実装にとどめてください。
- 要件以外の要件をどうするかは、エンジニアにお任せします。迷ったら相談してください。

## 期限

- 例：2020/08/01

## 親ストーリー

#13

**Comment by karokita** [comment]
@tokku5552 

- 一旦、アイコンのとこはまるくなったのですが、よくよく考えてみてると、
  - 今のスキーマに入ってなさそう
  - 画像アップロードを入れると格納先を考えないといけなそう
  - デフォルト（未登録時）どうするんだっけ
- というのが色々とみえてきたので、今回のタイミングではとるがよいかな、と思ってます。
- 何かとる対応でネックになりそうなところや影響出そうな部分あったら教えていただけるとです。


![Simulator Screen Shot - iphone12 - 2022-08-10 at 01 03 41](https://user-images.githubusercontent.com/96728192/183702015-7f156d73-9c72-4913-bd10-c87b652075f4.png)

**Comment by tokku5552** [comment]
@karokita 
UI的にアイコンを後で入れれるようにするなら、とりあえず子供のイラストでも置いておくと良いかも　と思いました!

**Comment by karokita** [comment]
@tokku5552 

ありがとうございます！とりあえず影響はなさなさそうと思って大丈夫でしょうか？
一応いれてみたのですが、3-5歳くらいの子どもで男女両方にいけそうなイラストあんまりない＆使ってみたあとのヒアリング時にアイコンどうやってアップロードするんですか？と問い合わせきそうなので、

- コメントアウトするor削除で対応
- アップロードとかの機能自体は落とす

とかでいったほうがユーザー体験的にはベストかなとおもうんですね〜
![スクリーンショット 2022-08-10 9 12 39](https://user-images.githubusercontent.com/96728192/183783079-cdacf11f-53fd-4496-a28b-783b3da43e9e.png)
