### ISSUE TITLE
マイページ - ViewModel/State/Repository部分実装

### ISSUE THREAD

**Issue by tokku5552** [pj-picbook/picbook#30]
## 概要

- 状態管理絡めたfirebaseとの連携部分まで実装する

## 要件

- 例：メールアドレスはログインしているユーザのメールアドレスを表示する
- 下記のイメージ図を参考にしてください。

- デザインは別途まとめて対応するので、Flutter 標準Widgetを使って簡易的な実装にとどめてください。
- 要件以外の要件をどうするかは、エンジニアにお任せします。迷ったら相談してください。

## 期限

- 例：2020/08/01

## 親ストーリー

#13

**Comment by tokku5552** [comment]
@karokita 
すみません、firestore使いたいので、`pj-picbook-dev`のオーナー権限頂いて良いでしょうか？

**Comment by pj-picbook** [comment]
@tokku5552 
念のため確認させてください！
リソース作成からは編集者でもいけるかなと思ったのですが、
どこらへんで必要か教えていただいてもよいでしょうか？

お手数なのですが権限周りとか請求とか発生しそうな時は、
それが必要な理由と一緒にコメントとありがたいです！

**Comment by tokku5552** [comment]
@karokita 
firestoreが設定されていなかったり色々漏れているためです。
権限渡したくないということであれば作業依頼する形にしましょうか？

**Comment by karokita** [comment]
@tokku5552 

いえ、権限渡したくないとかではないです！
会社とかで業務やってるとロール周りの管理がちゃんとしてなくてissueが発生していたりするので一応念のため把握したいというのがありました。
firestoreの設定をするためということで理解しましたので、オーナー権限付与しました。
作業終わったらお知らせいただけるとありがたいです。

**Comment by tokku5552** [comment]
@karokita 
ありがとうございます！firestoreをasia-northeast-1 テストモードでプロビジョニングして、ついでにAuthenticationのメールパスワード認証も有効にしておきました！
使用量は以下の画面で見れるので、気になるようであればこちらwatchしていただくのがいいかもです！
![スクリーンショット 2022-07-28 9 16 17](https://user-images.githubusercontent.com/69064290/181393818-6b1895f9-da75-4943-92a2-092f1e40afbc.png)

> 会社とかで業務やってるとロール周りの管理がちゃんとしてなくてissueが発生していたりする

そうですね、ただdev環境はできればこのままオーナー権限いただきたいです。ちょこちょこ設定が必要な場面が出てくると思うので、、、、
なにか設定変更した際は都度報告するようにしますね。

余談ですが、一応使用量と請求額というところで状態俯瞰できると思いますので、こちらもご確認いただければと思います。(おそらくBlazeにするまでは一切請求は発生しないと思います)
![スクリーンショット 2022-07-28 9 18 47](https://user-images.githubusercontent.com/69064290/181394020-20c80d23-5678-4185-81c7-af4fc3ef8abb.png)

**Comment by karokita** [comment]
@tokku5552

諸々の設定ありがとうございます！早い！！
Blaze プランに変更しましたので、cloud functionいじれるようになるかなとおもいます。

使用量みれるのよきですね〜
（あと上限設定もできるんですね。べんり！）

よく理解できましたので、オーナー権限引き続きよろしくおねがいします。

色々と都度の確認が細かくて恐縮です！
私自身が使ったことがないので、おそるおそる〜な部分もあり、
色々教えていただきながらすすめていけるとありがたいです。

**Comment by tokku5552** [comment]
- メモ
  - ViewModelのテストまでdone
  - WidgetTestと、できればfirestoreのインスタンスだけ分離してrepositoryもテストしたい
  - アーキテクチャ説明用に図を認める
