### ISSUE TITLE
Firebaseの環境構築(リポジトリ側 Flutter以外)

### ISSUE THREAD

**Issue by tokku5552** [pj-picbook/picbook#46]
## 概要

- firebase-cliあたりいれて、セキュリティルールやfunctionsのデプロイを行えるようにする
- こういうやつです！
  - https://github.com/flutteruniv/couple_todo/tree/main/firebase
  - 上記は無いですが、package.jsonが作られた状態のほうがいいかも
  - 上記リポジトリではテストライブラリにmocha使ってるようなこと書いてますが、今はjestが主流なので、jestで
  - 実際のテストやルール記載は行わなくて大丈夫です！
  - 上記リポジトリはHostingの設定も入ってますが一旦なくて大丈夫です！

## 要件

- firebase-cliが使えること。できればDockerで(Windowsの人もいるので)
- プロジェクトの紐付けがfirebasercにされていること(コマンドで設定が終わっていること)
- セキュリティルールがFirebaseのプロジェクトと同期されていること(コマンドで実行してれば同期されると思います)

#### 以下はできたらより良いが、PR膨れそうor時間かかりそうなら別ISSUEで
- GitHub Actionsでセキュリティルールのテスト＆デプロイ追加

## 期限

- 2022/08/05

## 親ストーリー

ここに親ストーリーのissue番号を記載する

**Comment by pj-picbook** [comment]
@tokku5552 

設定ですね〜！
ちなみに何をどこまでを決めると良い感じでしょうか？

料金プラン的なことであれば、サービスのユーザー数とかによって変わってきそうなので、最初はミニマムのプランになるかなあと思いました。
あとは実装する機能によっても変わりそうなので、どのタイミングで必要になるかによっても返答が変わりそうです！

現時点だと全てを想定し切るのが難しそうなので、各機能実装の際にfirestore/cloud storage/hosting/functionsを必要になったタイミングで、

- やろうとしている要件
- 決めなきゃいけないポイント
- どのプランがベストか

を伝えていただいて、それに沿って選ぶみたいなやり方だとやりやすいかなと思いましたがいかがでしょう？

**Comment by tokku5552** [comment]
どちらかというとfunctions使うなら`Blaze`にしておく必要があるという感じですね  
https://firebase.google.com/pricing?hl=ja
私は基本は遊びの環境以外は最初からBlazeにしてしまいます。が、無料枠は相変わらずあるので、よほどアクセスが来ない限りは請求はないです。(今の所私は1円も請求来てません)。
今回functions使うことになると思うので、このタスクをRomuさんが着手する前までに変更しておいていただけると 🙏

**Comment by karokita** [comment]
@tokku5552 

なるほど。
やはりfunctionsを使うことになるというのがまだ初のお話だったと思うので、
利用の用途伺っても良いでしょうか。
一応ざっくり読みましたが、今回どんな感じで使うイメージか教えてくださいー。

全然、Blaze設定するのはやぶさかではないのですが、
把握しているのと把握してないまま設定するのだと結構違うなとおもいまして

- 今回の仕様だとどのfirebaseのどのプロダクトを使って
- どのくらいのデータ量/件数が発生するのか　
- 大体どのくらいのユーザー数が発生した段階でかかりそうか

辺りは把握してから設定したいです！
（これ読む限りはそんなにすぐすぐはないと思うのですが　https://firebase.google.com/pricing?hl=ja )

**Comment by tokku5552** [comment]
@karokita 
> 今回の仕様だとどのfirebaseのどのプロダクトを使って
どのくらいのデータ量/件数が発生するのか　
大体どのくらいのユーザー数が発生した段階でかかりそうか

すみません、これは料金見積もりをしろという話でしょうか？  
ちょっとそこまでやるのは厳しいです。  
機能が固まっていない中でどのプロダクトを使うべきかを試行錯誤しているところですし、データの取得方法などで料金も変わるので、現時点で正確に見積もるのはほぼ不可能じゃないかなと思います。
ある程度プロダクトが形になった段階で、一通りテストしてみて、そのデータ量をもとに計算すればなんとなく出てくると思います。多分数千とか数万とかのユーザーがかなりアクティブに使わないと気にする金額にはならないんじゃないかなと思いますがわかりません。(アクティブでないユーザーが200人くらいいるアプリのプロジェクトではいままで1円もかかったことありません)

[他のissueでも話していますが](https://github.com/pj-picbook/picbook/issues/57#issuecomment-1196851465)、APIがオープンなものでなく、悪用される可能性があるのでクライアント側で持ちたくないという話が1点と、firestoreに今回同時に書き込みに行く箇所があるので、セキュリティルールと合わせて考えたときにfunctionsを使う場面が出てくるという話です。

**Comment by karokita** [comment]
@tokku5552 
形になった段階でデータ量もとに計算するでクリアになりそうですね！
また下記のご説明で背景もよく理解できました。ありがとうございます。

>他のissueでも話していますが、APIがオープンなものでなく、悪用される可能性があるのでクライアント側で持ちたくないという話が1点と、firestoreに今回同時に書き込みに行く箇所があるので、セキュリティルールと合わせて考えたときにfunctionsを使う場面が出てくるという話です。

こちらRomuさん着手前に対応しておきます！

**Comment by Romu1273x** [comment]
こちら作業開始しようと思いますが、以下をお願いしたいです。
・このプロジェクトで使うfirebaseの共有（必要なら権限も？）
・バックエンド用のリポジトリの作成（別リポジトリする？から検討）

**Comment by karokita** [comment]
@Romu1273x 
firebaseは、下記アクセスいただくとpj-picbook-devとpj-picbook-proがあると思うのでご確認ください。
権限も変更してみたので、gmailに招待メールがいってるかなと思います！
https://console.firebase.google.com/

リポジトリの場所は徳田さんにご確認いただくのがよさそうですね🤔　@tokku5552

**Comment by tokku5552** [comment]
@Romu1273x 
https://github.com/pj-picbook/picbook/issues/5 こちらのタスクの際に既に編集権限はふられているようです！メール来ていませんか？

 > バックエンド用のリポジトリの作成（別リポジトリする？から検討）

ひとまずプロジェクト直下にfirebaseというディレクトリ作成いただいて、そちらで設定いただければと思います！

**Comment by Romu1273x** [comment]
@karokita @tokku5552 
対応ありがとうございます！

リポジトリの件、了解しました。このリポジトリ内で作成します。

**Comment by tokku5552** [comment]
https://twitter.com/nabemasat

**Comment by Romu1273x** [comment]
メモ：Dockerで利用するNodeのイメージをどうするか？
参考プロジェクトだと「latest」になっていたが、v18になりそう。
現在のサポートされているバージョンがv16まで。
「16」、「16-alpine」辺りで検討中。

**Comment by Romu1273x** [comment]
@tokku5552 
すみません、既に①を参考に3番までにやってしまったのですが、②を参考にした方がよかったでしょうか？
①https://firebase.google.com/docs/functions/get-started?hl=ja
②https://firebase.google.com/docs/cli?hl=ja#mac-linux-auto-script

また、②の場合、firebase initを実行すると選択肢がいくつか出てくるのですが、今回だとどれが最適でしょうか？
調べた感じHostingを使っている記事が多かったですが、判断できませんでした。
![スクリーンショット 2022-08-04 9 27 50](https://user-images.githubusercontent.com/74139918/182737682-4afb5184-f379-46df-8f58-d4be6055099d.png)

**Comment by tokku5552** [comment]
@Romu1273x 
今回のやってほしいこととしてはすでに作成されているfirebase PJ(`pj-picbook-dev`)と連携することです。
Hostingは使うかわからないですが、少なくともFirestoreとStorageは使うことになっているので、最低限Firestoreの設定がされていればいいと思います。

これinitしたらわかりますが、べつに後から設定を追加することもできますし。削除することもできるので、色々試行錯誤していただければと思います 🙏 

完了しているかの確認としては、セキュリティルールを適当に書き換えて、ちゃんとデプロイできるかを基準にするといいかと思います！

**Comment by Romu1273x** [comment]
了解しました。
