### ISSUE TITLE
作品詳細画面のUI作成

### ISSUE THREAD

**Issue by karokita** [pj-picbook/picbook#48]
## 概要

作品詳細画面のUI作成

<img width="253" alt="スクリーンショット 2022-07-24 21 20 51" src="https://user-images.githubusercontent.com/96728192/180646808-9301bdb2-f6cd-4d8d-b255-36dfc2d73fda.png">

## 要件

- 表示要素
- Appbar
  - 作品タイトル　(※ _Book_ >title)
- 書影
  - 絵本の書影 　(※ _Book_ >mediumImageUrl)
- 書籍タイトル
  - 絵本の書籍タイトル (※ _Book_ >title)
- 作者
  - 著者名 (※ _Book_ >author)
- 出版社
  - 出版社名を表示 (※ _Book_ >publisherName)
- 詳細
  - 作品の詳細を表示 (※ _Book_ >itemCaption)
- 登録ボタン
  - テキスト
    -   ＋ 登録する 
  - 押下後の挙動は　#58 で定義

※データの連携は別タスクだが、参考までに記載
https://github.com/pj-picbook/picbook/blob/develop/docs/schema.yml

## 期限

- 2020/07/31

## 親ストーリー

#11

**Comment by Romu1273x** [comment]
@IshitaniKatuya 
@kawadon780 
cc: @tokku5552
作品詳細画面は検索画面と本棚画面から遷移するんですが、本の情報を作品詳細画面にどうやって渡す予定でしょうか？

今回だと状態管理はRiverpodなので、Riverpodで更新すると思ってます。
ただ、この前の1画面ごとにそれぞれ管理するとなるとそれが出来ません。（作品詳細画面でAPIを叩き直す必要がある）

本に関しては本の状態だけを管理するstateを作って、検索画面と本棚画面で更新。作品詳細ではそれを参照。というのが良い気がするのですが、どうでしょうか？

もし、1画面のごとにそれぞれ管理するっていう風にするなら、作品詳細画面でAPI or Firebaseから取得し直す必要がありそうです。（その場合、本棚からの遷移なのか？検索からなのか？を判定するための情報が入りそうです。）

**Comment by tokku5552** [comment]
> 本に関しては本の状態だけを管理するstateを作って、検索画面と本棚画面で更新。作品詳細ではそれを参照。というのが良い気がするのですが、どうでしょうか？

そうですね〜ここの仕様は本棚と検索画面でのデータの持ち方含めて一度みんなで話し合ってみるのもいいかもしれません 🤔
