### ISSUE TITLE
firebaseの準備

### ISSUE THREAD

**Issue by tokku5552** [pj-picbook/picbook#5]
## 概要

- firebaseのプロジェクトを作成 (dev/prd)
- devの方でfirestoreの初期設定とiOS/Androidのアプリ追加を行う
- Flutterのコード側でパッケージ追加、及びGoogle-Service.json等を配置してビルドが通ることを確認しておく
  - Google-Service.json等は.gitignoreに追加して、リポジトリにあげないようにしておくこと
- 各メンバーに適切な権限をあたえ、json/plistを取得できるようにする

## 詳細

- 例：ログイン画面を実装する。
- デザインは仮のものでOK
- 画面遷移

## 要件

- ここに要件を列挙する
  - こんな感じ

## 期限

- 例：2020/08/01

## タスク一覧

ここに本ストーリーに紐付くタスク番号を列挙する

**Comment by pj-picbook** [comment]
firebaseのプロジェクト作成doneしました。

@Ta23ka98 
プロジェクト招待しました！
一旦、権限をオーナーに変更させていただいたので、
リソースの作成からできるかなと思います！
アサイン変更させていただくので、ご対応可能でしょうか？

[プロジェクト名]
pj-picbook-dev

[やること]
- [ ] firebaseのプロジェクトを作成 (dev/pro)
- [ ] devの方でfirestoreの初期設定とiOS/Androidのアプリ追加を行う
- [ ] Flutterのコード側でパッケージ追加、及びGoogle-Service.json等を配置してビルドが通ることを確認しておく
- [ ] Google-Service.json等は.gitignoreに追加して、リポジトリにあげないようにしておくこと
- [ ] 各メンバーに適切な権限をあたえ、json/plistを取得できるようにする

**Comment by Ta23ka98** [comment]
@pj-picbook 
アサイン変更の旨、承知しました！
[やること]のリストについて、こちらで作業させて頂きます

作業の完了または、分からないことがあった場合は、また追ってご連絡させて頂きます👍

**Comment by Ta23ka98** [comment]
## 進捗報告
① iOS Simulatorにてビルド通りました！

とりあえず
・Firebase_core
・Firebase_auth
・Cloud_firestore
の3つをpubspec_yamlに追加した上で、ビルド通りました！

どの段階で「Firebaseが通っている」と言えるのか分かりませんが、これで大丈夫でしょうか？🤔
(pod installまで実行されていたので、大丈夫とは思うのですが...)

<img width="1407" alt="スクリーンショット 2022-07-20 17 42 01" src="https://user-images.githubusercontent.com/79580546/179948874-dc67fb3c-13e5-49f3-9ce5-6b75556e073e.png">

②Android Emulatorが起動できない

Fireabseプロジェクト関係なく、自分の環境に原因があるみたいです！

出来るだけ早く解決すべく、
・Flutter大学のGithubのissueへの投稿
・質問Zoom
で対応中です🙋

③質問：Firebaseの構成ファイル、どうやって.gitignoreに追加すべき？

具体的に、2つのことが分かりません...
・.gitignoreのどの部分に追加すべき？(そもそも書き方を知らないので、別途で調べる予定です)
・Info.plistも追加すべき？(Google-Service-info.plistの下のファイル。たぶん関係ない？)

<img width="1023" alt="スクリーンショット 2022-07-20 18 48 54" src="https://user-images.githubusercontent.com/79580546/179954460-92aece45-4355-4b0a-a85a-62e8aed8e807.png">

とりあえずの課題はAndroid Emulatorなので、質問Zoomなりで解決次第、また報告させて頂きます👍

**Comment by Ta23ka98** [comment]
Android Emulatorの件ですが、あっさり解決しました！
ちゃんと起動できる状態なので、FirebaseにてAndroidプロジェクトの追加に取り掛かりたいと思います💪

**Comment by tokku5552** [comment]
> ・.gitignoreのどの部分に追加すべき？(そもそも書き方を知らないので、別途で調べる予定です)

適当なところに書いてしまって良いと思います！
以下のようなのを末尾に追加するのはどうでしょう？
```
# firebase sdk keys
android/app/google-services.json
android/app/**/google-services.json
ios/Runner/GoogleService-Info.plist
ios/Runner/**/GoogleService-Info.plist
```

> ・Info.plistも追加すべき？(Google-Service-info.plistの下のファイル。たぶん関係ない？)

いえ、これはiosのビルドの設定ファイルなので、git管理下のままでお願いします 🙇

**Comment by Ta23ka98** [comment]
.gitignoreおよびInfo.plistの件について、承知しました！
必要なタスクを全て完了しましたので、プルリクを作成させて頂きました🙋

ちなみにプロジェクトの権限は、お返しした方がよいでしょうか？
(あまり分かっていないのですが、Firebaseコンソールからできるのでしょうか🤔)

**Comment by tokku5552** [comment]
> ちなみにプロジェクトの権限は、お返しした方がよいでしょうか？

私が答えることでも無いかもですが、おそらく開発期間中はいじることになると思うので、そのままで良いかと思います！

@karokita 
@Ta23ka98 
あと https://github.com/pj-picbook/picbook/pull/31 のプルリクがマージされたら同時にこのissueもクローズしちゃって良いですか？良ければ紐付けます

**Comment by pj-picbook** [comment]
@tokku5552 @Ta23ka98 
権限は一旦そのままで大丈夫です〜！

#31 のプルリクがマージされたら、
こちらのissueは全部タスク終わった状態になりますので、
クローズお願いいたします！

**Comment by Ta23ka98** [comment]
了解しました！そのままにしておきます🙆

その後のissueのクローズなど、よろしくお願いします🙇
