### ISSUE TITLE
floating action buttonの遷移

### ISSUE THREAD

**Issue by karokita** [pj-picbook/picbook#50]
## 概要

![スクリーンショット 2022-07-19 22 19 22](https://user-images.githubusercontent.com/69064290/179759992-f807c049-5a8b-441a-93ea-1535eeaf805d.png)

- floating action buttonを押下で、検索画面へ遷移 #27 

## 要件

- floating action buttonを押下で検索画面へ遷移する

## 期限

- 例：2020/08/01

## 親ストーリー

#10

**Comment by Ta23ka98** [comment]
@karokita 
こちらのissueをリオープンしたのですが、もう完成している気がします🤔

勘違いでなければ、どなたかが実装してくれた記憶があります。
こちらクローズしてしまって大丈夫でしょうか？
<img width="350" alt="スクリーンショット 2022-08-15 12 11 17" src="https://user-images.githubusercontent.com/79580546/184570992-ef3170fd-cd35-4d85-a3ef-4ba4a949b0ac.png">
