### ISSUE TITLE
ログインの機能実装（メールアドレス）

### ISSUE THREAD

**Issue by karokita** [pj-picbook/picbook#56]
## 概要
![スクリーンショット 2022-07-25 22 23 42](https://user-images.githubusercontent.com/96728192/180789644-cb9bf263-9c85-46ff-9f7a-bb29227dbe61.png)

- ログイン機能の実装

## 要件
- メールアドレスを使ってログインできる機能を実装

- 関連スキーマ
  - User:
    - id: string
    - name: string
    - email: string
    - linkedAccount: string ( Google | Apple )
    - bookshelfs: Bookshelf[]
    - ※詳細はスキーマ定義を参照　https://github.com/pj-picbook/picbook/blob/develop/docs/schema.yml

- 入力する情報
  - メールアドレス  （※ _User_ >email)
  - パスワード 

## 期限

- TBD

## 親ストーリー

#6

**Comment by Ta23ka98** [comment]
@pj-picbook 
#74 がクローズされたので、他の類似のissueもクローズしちゃって大丈夫でしょうか？🤔
(使われていない#54 #56 #60 #61のissue)

ログイン状態の監視&Userデータの追加は、すでに徳田さんが別issueで対応して下さっています🙌(#85)

また、新しいissueのアサインなどあればお願いしたいです🙋

**Comment by karokita** [comment]
@Ta23ka98 
おおー、おつかれさまでした〜🥳🎉

クローズしちゃって大丈夫です、お願いします！
別issue対応も了解です。

次のissueこちらの2つをお願いできますでしょうか？
https://github.com/pj-picbook/picbook/issues/86
https://github.com/pj-picbook/picbook/issues/50

**Comment by Ta23ka98** [comment]
@karokita 
了解です！アサインありがとうございます🙌
