### ISSUE TITLE
楽天書籍検索APIで書籍を検索できるようにする

### ISSUE THREAD

**Issue by tokku5552** [pj-picbook/picbook#57]
## 概要

- 開発に入る前に「[salon_app_doc の README.md](https://github.com/kboy-salon/salon_app_doc)」 を読んでください。
- 例：ログインボタンを実装

## 要件

- 例：メールアドレスはログインしているユーザのメールアドレスを表示する
- 下記のイメージ図を参考にしてください。

- デザインは別途まとめて対応するので、Flutter 標準Widgetを使って簡易的な実装にとどめてください。
- 要件以外の要件をどうするかは、エンジニアにお任せします。迷ったら相談してください。

## 期限

- 例：2020/08/01

## 親ストーリー

#12

**Comment by tokku5552** [comment]
@kawadon780 
すみません、わかりずらかったので、別途issue立てました！
楽天APIのレスポンスのsutatus codeについて、迷っていることって何でしょうか？  ステータスコードごとにすべてハンドリングする必要があるか？とかそういうことです？

**Comment by kawadon780** [comment]
@tokku5552 　CC:@karokita
 
Isuueありがとうございます！

色々すみません、依頼が抽象的過ぎました。。。

>  ステータスコードごとにすべてハンドリングする必要があるか？とかそういうことです？
はい、まずはここの観点が気になっておりましてver1.0では考慮するべきかという所になります。

温度感としては、オフラインに関しては今回考慮しなくていいと返信いただいたので、細かいエラーも結構気にしなくていいのかなーとか思ったりしました。

よくあるケースだと「429 too_many_requests(リクエスト過多 (各ユーザ制限値超過))
」でしょうか？検索なら連打するような状況はあると思うので、一時的にレスポンスが成功しないから「時間をおいて再度検索ください」と表示したりするのが親切ですが、それは面倒なので「通信に失敗しました」みたいなおおざっぱなダイアログで実装して、各画面の通信系のエラーもそれを流用するとかそういう方針が決まればいいかなーと思っています。

**Comment by pj-picbook** [comment]
- 200じゃなかったらエラー対応

**Comment by tokku5552** [comment]
これ実装はUIのあとということで、急いでないのですが、`429 too_many_requests(リクエスト過多 (各ユーザ制限値超過)`というの見ていて、そういえばアクセスキーとかシークレットとか使ってAPI叩くとかであればfunctions経由にしたほうが良いかも？と思いました。
functionsから叩けばリクエストのレート制限とかもこちらで調整できそう。

## 背景
Bookに持たせる情報を今回はFirestoreに保存せず、必要なときに毎回APIを叩くという設計にしています。(でないと例えばはらぺこあおむしの情報が場合によってはいくつもfirestoreに保存される事になり非効率と考えたため)。  
ですが、functions経由するなら、一度叩いてfirestoreに保存しておいて、次回以降はfirestoreから情報取るようにすれば重複することもないしAPIのレート制限の緩和もできるかなと思いました。

忘れないようにメモしただけなので、実際に着手したらもうちょい詰めましょう！

**Comment by kawadon780** [comment]
回答ありがとうございます。

functionsも検討承知しました。
functionsってキャッシュとかももしかして持たせたり可能でしょうか？

**Comment by kawadon780** [comment]
進捗こっちに貼ってapiの中身みてますが、なんか絵本ジャンル以外が返却されてるので、リクエスト時にジャンルIDも指定しないといけなそうですね。。。そこら辺も精査していきます。

https://github.com/pj-picbook/picbook/issues/27#issuecomment-1198335078

**Comment by tokku5552** [comment]
@kawadon780 
> functionsでFireStoreに保存してキャッシュみたいに使うイメージですかね？

イメージそんな感じです！#27の動画見た感じ、こうサクサク動かすにはAPI直接のほうがやっぱりいいのかも？とか思いました 🤔 
どういう場合にfunctinsつかってどういう場合に直接叩くのか整理したほうが良さそうですね 👀

**Comment by kawadon780** [comment]
@tokku5552 なるほどです！ありがとうございます！

> どういう場合にfunctinsつかってどういう場合に直接叩くのか整理したほうが良さそうですね 👀
承知しました。自分の方でも調べてみますm(_ _)m

**Comment by tokku5552** [comment]
- Slackにて会話した内容のサマリ
  - このチケットでは`まず検索結果を本棚に登録する`ことと`ジャンルでのフィルター`のみ行いその他の問題は別issueに分けて一旦優先度下げる。
  - functionsの採用有無については以下で検討
  - #66

**Comment by karokita** [comment]
@kawadon780 

かわどさんもう調べてるかもなのですが、
楽天ブックスのジャンルIDとジャンル名がのってたのでシェアです！
https://nokin-taro.com/rakutenbooks_genreid/

下記2つが絵本系のジャンルIDになるようです。
001003
007616

**Comment by kawadon780** [comment]
@karokita 
いえ、まだ調べてなかったです。助かりました！

そこまでまだ調査してないのですが、ジャンルは一つしかリクエストできないっぽいのと「007616」の方が検索ひっかからない？ぽいので「001003」を一旦採用したいと思います。

<img src =https://user-images.githubusercontent.com/54085013/182004405-25b4a2aa-0dcd-4e1b-9078-544a64ef06f9.png width = 300 height =600>
