### ISSUE TITLE
作品詳細画面の本棚登録機能

### ISSUE THREAD

**Issue by karokita** [pj-picbook/picbook#58]
## 概要
作品詳細画面の本棚登録機能
<img width="253" alt="スクリーンショット 2022-07-24 21 20 51" src="https://user-images.githubusercontent.com/96728192/180646808-9301bdb2-f6cd-4d8d-b255-36dfc2d73fda.png">

## 要件

- 作品詳細画面で、登録するボタンを押下すると本棚に登録
  - 押下後の挙動
    - ポップアップが表示　内容は　#51  と共通
      - 本棚に登録しました！
  - 遷移先
    - ポップアップ表示後、本棚画面へ遷移 
    
- 既に登録済みの本に関しては、ボタン非アクティブ（※実装難易度によっては別挙動も検討）

## 備考
- 検索から来た場合の作品詳細画面と本棚から来た場合の作品詳細画面を別画面として準備するという話が出ていたので、実装にあたっては徳田さんと要ディスカッション

## 期限

- TBD

## 親ストーリー

#11

**Comment by Romu1273x** [comment]
ユーザーフロー確認したんですが、どっちもAPI叩かずに遷移前の画面から情報引っ張って来れそうなんですが、何か認識間違ってますか？

遷移前の画面
・本棚：本棚画面でfirebaseから本の情報を取得　→ 作品詳細画面に渡す
・検索画面：検索一覧で楽天APIから本の情報を取得　→ 作品詳細画面に渡す

**Comment by pj-picbook** [comment]
@Romu1273x 

すみません。APIの情報を取り扱うな、というところで本棚機能をおすすめしたのですが、現状だとAPI叩くのは、検索機能のみになってますね。

ということで、Romuさんの認識は特に間違ってないかと思われます！
昨日の議論だとAPIを毎回叩く方が楽かなー、みたいな話が一瞬出てた感じでしたが、遷移前画面から引っ張ってこれたらそれが一番良さそうな気もします。

**Comment by Romu1273x** [comment]
了解しました。
このアプリ場合だとAPI叩き直す必要ない（リアルタイムである必要がない）と思うので、画面からという想定にしておきます。

**Comment by Romu1273x** [comment]
@kawadon780 
すみません、検索画面で検索をするとアプリがクラッシュしてしうのですが、かわどさんが実装している時に同様の現象ありませんでしたか？
検索したリストから遷移しようと思ってるのですが、落ちてしまってデバックが出来ないという状態です。

**Comment by Romu1273x** [comment]
@tokku5552 
本の情報をfirebaseに登録するにあたって、その時選択されている本棚（bookshelfs.id）が特定出来ない気がします。
先に本棚の方でその辺の情報を保持するNotifierを作った方が良い気がします。
あと、その時にfirebase上に現在選択されている本棚がどれか？っていう情報が必要な気がしてますが、どうでしょうか？
（仕様把握しきれてない気がしているので、おかしな事言ってたら教えてください。）

@kawadon780 
かわどさんも同じようなタスクやると思うんですが、どう考えてましたか？

**Comment by kawadon780** [comment]
@Romu1273x 
とりあえず本棚は最初に登録した一つだけで想定してました！いずれ複数になるとは思いますが、その時はuserで持つか、同じユーザーでもいろんな本棚を持つのであればローカルなどで持つしかないかなーと思っていました。

**Comment by Romu1273x** [comment]
> とりあえず本棚は最初に登録した一つだけで想定してました！

というと、users配下のbookshelfsサブコレクションで1番上のドキュメントIDを使ってbookを登録する感じですか？

**Comment by kawadon780** [comment]
@Romu1273x 
ですね！現状の構造でコード的にいえばリスト？で多分かえってくるので[0]でとればいいのかなーと。
今って本棚を複数登録する所ない？のかと思って一旦その想定で作業してました。

**Comment by Romu1273x** [comment]
@kawadon780 
了解しました。ありがとうございます！
じゃあ、自分もそのつもりで実装しようと思います。

**Comment by kawadon780** [comment]
@Romu1273x 
レビューしていただいのでご存じかもしれませんが、SearchBookPageNotifierに「registerBook」を作成しました。
こちらにbookを渡し登録いただければと思います。

**Comment by Romu1273x** [comment]
@kawadon780 
了解しました。ありがとうございます！

**Comment by Romu1273x** [comment]
ブランチ：#58_book_detail_function
で対応。
