### ISSUE TITLE
ThemaDataを設定する

### ISSUE THREAD

**Issue by karokita** [pj-picbook/picbook#59]
## 概要
- ThemaDataを設定する

## 要件

- 基本のルールを検討
テキストフォント
Button系Widgetのデフォルト
カラー
- main.dartに設置
Themaで設定できるプロパティ一覧 https://itome.team/blog/2019/12/flutter-advent-calendar-day12/
color class https://api.flutter.dev/flutter/material/Colors-class.html

- 例
https://twitter.com/_mono/status/1169776338661605376?s=20&t=8RjVB6ym_q5nsCi0lerI9w
https://material.io/design/material-studies/about-our-material-studies.html
https://m3.material.io/

- 便利ツール
カラーを選択するとMaterial themaを自動でbuildしてくれる　https://www.figma.com/community/plugin/1034969338659738588

## 指定内容

- primaryColor
- accentColor
- AppBarTheme class　F8F5EE　https://api.flutter.dev/flutter/material/AppBarTheme-class.html
- bottomAppBarColor　E5D1C6
- scaffoldBackgroundColor　
- cursorColor
- hintColor
- iconTheme
- pageTransitionsTheme

https://itome.team/blog/2019/12/flutter-advent-calendar-day12/
https://algorithm.joho.info/flutter/theme-property-flutter/

## 期限

- 2020/08/01

## 親ストーリー
なし

**Comment by karokita** [comment]
@tokku5552 @kawadon780 @Romu1273x @hironobu-kkk @Ta23ka98 @IshitaniKatuya 
いろいろと子供向けのアプリみてたんですが、パキッとした色が多かった&最近くすみカラーがはやってるので、透け感のある感じにしたいなと思って仮の色合いでスプラッシュと本棚のイメージつくってみました。タイトル適当です。

思考錯誤の過程と、ターゲットが近いアプリの画像をfigmaに貼ってます。（figma→左端のPages→トンマナ)
https://www.figma.com/file/LFlpRBi5CMWRJNMCnElqaY/picbook?node-id=303%3A8

こういう色とか雰囲気の方がいいんじゃない？などあればぜひ遠慮なくご意見ください！
明日のお昼くらいまでになければ、一旦これベースでThemaDataの色やフォントなどえらんでいきます。

![スクリーンショット 2022-07-30 16 03 14](https://user-images.githubusercontent.com/96728192/181879034-318366ab-6422-4c8b-872d-58e9de784318.png)

**Comment by Ta23ka98** [comment]
@karokita 
全体的にいい感じだと思います！

くすんだ感じが、絵本や紙芝居みたいなイメージを感じます👍
ただ、ちょっと大人っぽすぎる色味な気がします🤔

絵本といえば、[偕成社の真っ白な表紙](https://www.kaiseisha.co.jp/?post_type=books&series_slug=%e3%82%a8%e3%83%aa%e3%83%83%e3%82%af%e3%83%bb%e3%82%ab%e3%83%bc%e3%83%ab%e3%81%ae%e7%b5%b5%e6%9c%ac)が思い浮かびます。
また、[絵本は子供が見やすい工夫をしている](https://bre-men.co.jp/bookshelf/detail_5.html)みたいです。

なので、赤・青・緑・黄色の原色、あるいはそれを薄めた色が良いかも？
(背景が)あえて真っ白というのも良いかもです🙌

**Comment by tokku5552** [comment]
@Ta23ka98 @karokita お二人の意見みてふむふむ 🤔 と見ていたんですが、一旦ペルソナを定義しても良いのかなと思いました。 ターゲットはお伝えいただいたと思いますが、そのターゲットがどのように使うか、普段どのようなことを行っているのかの認識が少しずれている気がします（？）  
親のスマホに入れて親が使う？共用のiPadがある想定？子供にスマホをもたせている想定？　でこの辺が変わるのかなぁと思ったり 🤔 
個人的には @karokita の淡い感じ好きです。

**Comment by karokita** [comment]
@Ta23ka98 @tokku5552 

ご意見ありがとうございます！
まさたかさんの記事おもしろいですね。確かに年齢によって好ましい色がありそうな。

今、想定しているのは自主的にスマホをいじることのできる3-5歳のこども&大人です！
徳田さんおっしゃるようにペルソナ定義してまとめていくと認識あわせによさそうだな、とおもいました。

一旦、今回のでテーマデータを設定しつつ、
ペルソナ定義&画面のカラーバリエーションを何パターンか用意して、
インタビューでどれが好きか聞いてみる→第二弾で対応
とかもありかもですね...🤔
