### ISSUE TITLE
未ログイン時の画面作成

### ISSUE THREAD

**Issue by tokku5552** [pj-picbook/picbook#7]
## 概要
![スクリーンショット 2022-07-19 22 17 49](https://user-images.githubusercontent.com/69064290/179759686-45635884-d100-4deb-b0de-920bdece830e.png)

- 未ログイン時の画面作成

## 要件

- 表示要素
  - ロゴ ※まだないので何か画像を入れられるようにする
  - アカウント保持ユーザーへの案内
    - 案内テキスト
      - アカウントをお持ちの方
    - ボタン
      - ログイン
    - 遷移先
      - ログイン画面へ遷移 #9 
  - 未登録ユーザーへの案内
    - 案内テキスト
      - 初めてご利用の方 
    - ボタン（※実装難易度によって、要検討。ミニマムはメールログインのみ）
      - メールアドレスで登録
      - googleで登録
      - Appleでサインアップ
    - 遷移先
      - 新規登録画面へ遷移 #8 
  - 注意書き
    - テキスト
      - 登録/ログインすることで、[利用規約]※1と[プライバシーポリシー]※2に同意したものとみなされます。 
    - 遷移先
      - ※1 利用規約へ遷移
      - ※2 プライバシーポリシーに遷移

## 期限

- 2020/07/26

## 親ストーリー
#6

**Comment by karokita** [comment]
@Ta23ka98 

内容アップデートしました！ご確認よろしくお願いします。

**Comment by Ta23ka98** [comment]
アップデートお疲れ様です！確認させて頂きました🙋

**Comment by Ta23ka98** [comment]
何度もすみません、基礎的なことで2つ質問があります🙇

・新しく作業を始める準備としては、リモートリポジトリを「プル」で合っているのでしょうか？
(以前の作業時、すでに「リポートリポジトリをクローン→プルリク作成→マージ」の流れを行っています)

・その場合、ブランチはmainとdevelop、どちらをプルすれば良いのでしょうか🤔

最初はReadmeにあるvimeoを参考にしようとしたのですが、視聴できないようなのでKBOYさんに打診中です
(「このショーケースは非公開です」と表示され、パスワード入力を求められます)

**Comment by Ta23ka98** [comment]
こちらの質問ですが、vimeoの動画が視聴できるようになって解消しました👍
お騒がせして申し訳ありません🙇

**Comment by Ta23ka98** [comment]
あと微調整で画面が完成するのですが、ちょっと質問があります🙋
ファイルを置くディレクトリは、新しく作っても問題ないでしょうか？
<img width="1400" alt="スクリーンショット 2022-07-25 21 34 59" src="https://user-images.githubusercontent.com/79580546/180778564-c555df9b-ef40-4cf3-b74e-ad4ea935a7df.png">




元々はLoginPageという名前で画面を作っていました。
ところがログインやサインインは別で画面を作るので、Loginという名前(とディレクトリ)は使えません。

そこで、presentationにfirstというディレクトリを作って、そこに置こうと考えています。
(ついでに、FirstPage以外にわかりやすい名前があれば助言を頂きたいです🙇)

**Comment by karokita** [comment]
@Ta23ka98 
基本のディレクトリ構成に沿っているので全く問題ないです！
（こうやって都度つくるよー、ってやりとりしながらディレクトリ作成すると混乱なくてよいですね）

特に違和感なかったので、FirstPageでよいとおもいます。

**Comment by Ta23ka98** [comment]
了解しました！
すみません。また別の疑問があります🙇

画面の作成が完了した場合、この画面を初期画面にしても問題ないでしょうか？
それともスクショ(現在の初期画面)のように、ボタンで遷移できるようにした方が良いでしょうか🤔
<img width="352" alt="スクリーンショット 2022-07-25 21 55 34" src="https://user-images.githubusercontent.com/79580546/180782801-aafd1a01-2c0e-4518-8224-f82e9c8b9828.png">

**Comment by karokita** [comment]
@Ta23ka98 
こちらは、ボトムナビが表示されてないこともあり、
挙動確認のためにボタンが配置されてるのかな？と思いました。

諸々が整って切り替えるまでは、
一旦ボタンで遷移できるような対応でお願いできますでしょうか。（今のところ一番影響範囲すくなそうなので）

**Comment by Ta23ka98** [comment]
@karokita 
承知しました！
何度もありがとうございます🙌

**Comment by tokku5552** [comment]
@Ta23ka98 
一応作業切のいいところで都度作業ブランチにcommit & pushしていただいても大丈夫です？現状リモートブランチに#7のブランチがなさそうなので 🤔

**Comment by Ta23ka98** [comment]
@tokku5552 
失礼しました、急ぎpushします！
もうちょっと小まめにpushするようにします🙇

**Comment by Ta23ka98** [comment]
ひとまず完成しましたが、2つ質問です🙋

1. Podfile.lockはコミットしない方が良かった？
2. url_launcherのパッケージは導入した方がいい？
(利用規約やプライバシーポリシーへの画面遷移のため)

他になにか問題があれば、仰って下されば助かります👍

**Comment by Ta23ka98** [comment]
@pj-picbook 
[Flutterアプリ内でWebページを表示する方法](https://zenn.dev/tsuruo/articles/56f3abbb132f90)について調べました！

結論から申し上げると、
・Web埋め込み表示([webview_flutter 3.0.4](https://pub.dev/packages/webview_flutter))
・アプリ内ブラウザ起動([url_launcher 6.1.5](https://pub.dev/packages/url_launcher))
の２パターンがあるようです。

見た目や実装方法ほぼ同じですが、カスタマイズ性は前者が優れているようです。
個人的にはどちらでも良い気がしますが、いかがでしょうか？🤔

**Comment by karokita** [comment]
@Ta23ka98 

調査、ありがとうございます。
貼っていただいた記事わかりやすいですね👍

細かくカスタムができるということで、Web埋め込み表示([webview_flutter 3.0.4](https://pub.dev/packages/webview_flutter))でおねがいできますでしょうか！

**Comment by Ta23ka98** [comment]
@karokita 
承知しました！パッケージの導入をさせて頂きます🙋
完了後は、気にせずプルリク作成をして大丈夫でしょうか？

すっかり忘れていましたが、遷移後の画面(利用規約のページ)はどうしましょう🤔
おそらく別のissueを立てることになりますが...

**Comment by karokita** [comment]
@Ta23ka98 
導入よろしくおねがいします！

そですね。おとといのミーティングでがんがんいこうぜ！
となりましたので完了後は気にせずプルリク作成して大丈夫です！
（ブランチはissueごとにきる感じでお願いします🙋‍♀️)
こわい時は画面ごととかでslackで質問しながらでもだいじょぶですw

あと、遷移後画面の画面たしかにです。
プラポリ利用規約は今、絶賛文言を用意してるとこなので、

- 別issueを立たさせていただいて、その時対応
- 一旦は仮のURLでいれといていただく、

みたいな対応でいかがでしょう？

**Comment by Ta23ka98** [comment]
> * 別issueを立たさせていただいて、その時対応
> * 一旦は仮のURLでいれといていただく、
> 
> みたいな対応でいかがでしょう？

確かにそれが良いと思います!👍

> 完了後は気にせずプルリク作成して大丈夫です！

了解しました！
因みにプルリクのレビューは、 @karokita さん自身にも見て頂いた方がいいかもです
(ちょっとUIの背景が暗い気がするので...)

**Comment by Ta23ka98** [comment]
2点について、念のため共有しておきます🙋

・WebView(利用規約など)のページへは、とりあえず"画面遷移"で実装してあります
[以前の記事](https://zenn.dev/tsuruo/articles/56f3abbb132f90)の挙動は、厳密にはネイティブの挙動を呼び出したものです(一応、似たものに[BottomSheet](https://www.choge-blog.com/programming/flutter-bscreenbottom-show-sheer/)があるみたいです)

・遷移する為の画面が必要なので、agreement_pageディレクトリ、同ファイル、同ウィジェットを実装しました。
利用規約もプライバシーポリシーも、このウィジェット１つで表示できます。

**Comment by karokita** [comment]
@Ta23ka98 
このメッセージが出ていっこうにビルドができない症状がでてます
（かれこれ2時間くらい・・）

```
Running Xcode build...                                                  
 └─Compiling, linking and signing...     
```

わたくし解消までに時間がかかりそうで、
お手すきのときに画面キャプチャ貼っていただけるとありがたいです！🙇‍♀️

**Comment by Ta23ka98** [comment]
@karokita 
承知しました🙋
<img width="353" alt="スクリーンショット 2022-07-29 8 18 52" src="https://user-images.githubusercontent.com/79580546/181652916-aa02d737-b8eb-4b79-8201-5c6fe38512a4.png">

**Comment by karokita** [comment]
@Ta23ka98 

すごい！！！！
ワイヤーと色味がほぼ同じでびっくりしました笑

ありがとうございます。私からは問題ないと思いました。
後々調整するので、これから画面作成いただくときの色味は白黒とかでもだいじょぶです🙆‍♀️

@tokku5552 
大変申し訳ないのですが、相変わらずビルドエラー続いており、
コード部分のレビューお願いできるとありがたいですmm（もしくはどなたかアサインいただくなど！）

**Comment by karokita** [comment]
@Ta23ka98 
プライバシーポリシーと利用規約、github pagesで作成することにしました！
URLはこちらでいければと思うので、よきタイミングで差し替えお願いします。

プライバシーポリシー：https://pj-picbook.github.io/picdoc/docs/privacypolicy.html
利用規約：https://pj-picbook.github.io/picdoc/docs/terms.html

※利用規約はまだ作成中なので、privacypolicyのみ中身がある状態です。

**Comment by Ta23ka98** [comment]
@karokita 
承知しました！👍
