### ISSUE TITLE
codecov連携

### ISSUE THREAD

**Issue by tokku5552** [pj-picbook/picbook#72]
## 概要

- codecovと連携してカバレッジのレポートをPR時に見れるようにする

## 要件

- 例：メールアドレスはログインしているユーザのメールアドレスを表示する
- 下記のイメージ図を参考にしてください。

- デザインは別途まとめて対応するので、Flutter 標準Widgetを使って簡易的な実装にとどめてください。
- 要件以外の要件をどうするかは、エンジニアにお任せします。迷ったら相談してください。

## 期限

- 例：2020/08/01

## 親ストーリー

ここに親ストーリーのissue番号を記載する

**Comment by karokita** [comment]
@tokku5552 
codecovのトークン入れました！前回のお話にあったコメントアウト部分の対応できると良いかなと思ったのですが、該当箇所教えていただいても良いでしょうか？

**Comment by karokita** [comment]
おおーなるほど。ありがとうございます！
外したものをプルリクだしましたので、ご確認よろしくお願いします🙏
