### ISSUE TITLE
新規登録・ログイン機能の実装

### ISSUE THREAD

**Issue by pj-picbook** [pj-picbook/picbook#74]
## 概要

![180789644-cb9bf263-9c85-46ff-9f7a-bb29227dbe61](https://user-images.githubusercontent.com/106081460/182428683-8e435ad0-2aa7-40b6-b0b1-8e3e998d4d4d.png)
![180596002-d52e44a2-b153-416b-9330-7f533fb96f10](https://user-images.githubusercontent.com/106081460/182428689-1af57156-676f-4d54-a7f1-f1715065348b.png)

## 要件
- ログイン・新規登録機能の実装を行う
- 新規登録ができる
- ログインができる
- ログイン有無で画面出しわけする（ログイン・新規登録機能の監視)
　authStateChanges
　https://github.com/flutteruniv/couple_todo/blob/main/lib/infrastructure/firebase_auth_repository_impl.dart#L16

※バラバラになってたタスクをこちらのissueに集約。

## 期限

- 2020/08/09

## 親ストーリー

#6

**Comment by Ta23ka98** [comment]
@tokku5552 
確認なのですが、現在は #46 でFirebaseのセットアップ中という考えで間違い無いでしょうか🤔
他にできることがあれば、ご教示お願いします🙇‍♀️

とりあえず僕としては、リポジトリを作ってhooks_riverpodなどの使い方を試しているところです。

**Comment by tokku5552** [comment]
@Ta23ka98 いえfiresotreはもうアプリから使えるようになっていますし、https://github.com/pj-picbook/picbook/pull/67 のプルリクでは実際にfirestoreから値をとるコードをすでに記載してマージ済みです！
#46 はセキュリティルールをこのリポジトリで管理したり、functionsを開発したりするようの設定なので、アプリの開発とは直接関係ないです！

**Comment by Ta23ka98** [comment]
@tokku5552 
了解です！
とりあえず一通り勉強が終わったら、少しずつコミットしていきます🙋

**Comment by Ta23ka98** [comment]
2点、疑問があります🙋

1. 生年月日は必要か
#54 にて触れられていて、#13 にて議論中ですが...
-必要なら[DatePicker](https://garmi.blog/2020/03/01/flutter-cupertinodatepicker%E3%81%A7%E6%97%A5%E4%BB%98%E3%81%AE%E3%81%BF%E9%81%B8%E6%8A%9E%E3%81%97%E3%81%9F%E3%81%84/)を実装
-不要なら削除
したいと思います。
(あとFirebaseAuthを使った新規登録も)

2. ログアウト機能はどのページに実装するか
確認不足なだけかもですが、他のページへの実装は大丈夫でしょうか🤔
ないと色々困ると思うので、完成後はとりあえずボトムナビゲーションにFABを置いて、そこに実装しようと思っていますが...

**Comment by karokita** [comment]
@Ta23ka98 
1.生年月日は最終的には必要です！絵本は対象年齢というものがありまして、レコメンドに関わってくるので必要になってきます。ただし、実装が難しいなどの場合は、生年月日は初期対応しない、というはあるかなと思ってます。
（こんな感じで、絵本には対象年齢があるのです → https://www.fukuinkan.co.jp/bookguide/#osusume）

2.ログアウトはマイページに実装予定です
#13 
![スクリーンショット 2022-07-23 17 21 50](https://user-images.githubusercontent.com/96728192/180597003-d6b01466-e64f-47c3-9c6c-7c85460d5128.png)

**Comment by Ta23ka98** [comment]
CupertinoDatePickerの日本語化に手間取ってます...
[記事](https://www.choge-blog.com/programming/fluttercupertinodatepicker%E3%81%AE%E3%83%AD%E3%82%B1%E3%83%BC%E3%83%AB%E3%82%92%E8%A8%AD%E5%AE%9A%E3%81%99%E3%82%8B%E3%81%AB%E3%81%AF%EF%BC%9F/)を参考にやったのですが、上手くいきません。

とりあえずpushして後回しにして、今はFirebaseAuthに取りかかりたいのですが、問題ないでしょうか？🤔

<img width="1038" alt="スクリーンショット 2022-08-06 17 25 05" src="https://user-images.githubusercontent.com/79580546/183241261-80b7a586-7833-46d5-931e-4ca191f1b0e8.png">

**Comment by Ta23ka98** [comment]
@tokku5552 
user.dartにpasswordという値を追加したいです。
この場合、
- user.freezed.datrファイルとuser.g.dartファイルを削除
- user.dartにpasswordを追加
- 改めてコード生成
という流れで問題ないでしょうか？🤔

<img width="641" alt="スクリーンショット 2022-08-07 22 50 02" src="https://user-images.githubusercontent.com/79580546/183294055-50033ef1-94fd-40cf-810b-e39a1c7f78f3.png">

**Comment by tokku5552** [comment]
@Ta23ka98 
フィールドの追加方法という意味では
`user.freezed.datrファイルとuser.g.dartファイルを削除`　この作業はいらないです。自動で削除されます！

ただ、Userエンティティはfirestoreのusersコレクションに入れる値だけを保持しておきたいので、passwordは追加しないでほしいです！Authenticationはその場でfirebaseに送るだけで、firestore側で永続化しない想定です！そうでないならauthentication使う意味があまりないので 🤔

**Comment by Ta23ka98** [comment]
@tokku5552 
ありがとうございます、了解です🙋

> passwordの追加は不要

よく考えたらそうでした!
コントローラーの実装の流れで、勘違いしていました😅

> Authenticationはその場でfirebaseに送るだけで、firestore側で永続化しない想定

ここの理解が浅く、コントローラーの引数の書き方が合っているか悩んでいます🤔
具体的に悩みとは、

- そもそもHookConsumerWidgetを使用 & UserRepositoryを監視して良かった？
- コントローラの引数(ユーザ名など)は`text: state.name`でOK？
- passwordのコントローラの引数は、どうすればいい？(StatefulWidgetのように、`final String password = ""`?)
といった感じです

基本的には[ganさんの記事](https://zenn.dev/ryota_iwamoto/articles/firebase_auth_and_riverpod)のように実装するつもりですが、Riverpodやアーキテクチャなどでちょっと混乱している状態です。

お手数ですが、よろしくお願いします🙇

<img width="531" alt="スクリーンショット 2022-08-07 23 41 49" src="https://user-images.githubusercontent.com/79580546/183297024-bfc903cb-9219-4052-a25c-3b57a9d0e1bd.png">

因みにこれまでの作業の流れとしては...

1. mypage_notifier.dartと同じように、signup_page_notifier.dartを作る
2. mypage.dartと同じように、SignUpPageをHookConsumerWidgetにする
3. コントローラーの引数を[こちら](https://github.com/tokku5552/flutter_ddd_riverpod/blob/main/lib/presentation/todo_detail_page.dart#L13)と同じでよいか悩む

といった感じです。
(理解中とはいえコピペが多いので、ちょっと自信がない感じです😅)

**Comment by tokku5552** [comment]
@Ta23ka98 
コントローラーと言っているのはXXXNotiifierのことで良いですかね？

> コントローラの引数(ユーザ名など)はtext: state.nameでOK？

この部分が少し切り分けが必要で、状態を**読む**のか、状態を**更新する**のかで、stateからとってくるかnotifier.xxxというメソッドを呼ぶのかが変わります。
ちなみに useTextEditingControllerをインスタンス化するときの引数はあくまで初期値なので、最初に表示しておきたい値を入れておけば良いと思います！

これhttps://github.com/pj-picbook/picbook/pull/80/files/8a17d1ffa996c9fa0cb05ef303d217d73d0e1f1d#diff-cd22b11e8ac794466d51d0fc8f01254035a0f3b00dfe1c3126a52f839ddf107e の`lib/state/searched_book.dart`のように、stateを宣言したほうが良いかもです 🤔

**Comment by tokku5552** [comment]
@Ta23ka98 
結構空中戦になりそうなので、よければ一旦DraftでPR作ってみてもらっても良いでしょうか？そうすると私からもいま @Ta23ka98 さんがどう実装しようとしているのかが見えるので 👍

**Comment by Ta23ka98** [comment]
@tokku5552 
なるほど、ありがとうございます！

> ちなみに useTextEditingControllerをインスタンス化するときの引数はあくまで初期値なので、最初に表示しておきたい値を入れておけば良いと思います！

こちらと記事を参考にしつつ、やってみようと思います👍
