### ISSUE TITLE
本棚画面を入れ替える

### ISSUE THREAD

**Issue by karokita** [pj-picbook/picbook#77]
## 概要

本棚画面を入れ替える

## 要件

入れ替える
・bookshelf_page.dart
・book_shelf_page.dart　
・main.dart
・bottom_navigation_page.dart
・tab_item.dart

## 期限

2022/08/07

## 親ストーリー

#10

**Comment by karokita** [comment]
＠みなさま
本棚画面をポンデさんの作ったものに入れ替えたいとおもったのですが、うまくいかずです...🫠
調べてみているのですが、もしこれはこうするとよいよ、などありましたらアドバイスいただけると非常にうれしみです..！

<img width="986" alt="スクリーンショット 2022-08-06 16 19 29" src="https://user-images.githubusercontent.com/96728192/183239005-f2f17806-1e47-4149-8a5b-6a203c9a006d.png">
<img width="985" alt="スクリーンショット 2022-08-06 16 19 32" src="https://user-images.githubusercontent.com/96728192/183239011-0e8a22e4-c3ca-4d4c-808b-ecbafd692c74.png">

**Comment by kawadon780** [comment]
@karokita 
これ自分も対応に悩んだんですが、statelessのメンバ変数は初期化が必須でかつ定数値じゃないと、デフォルトのコンストラクタに「const」をつけれないんですよね。
ここではdummyListがlistで定数値じゃないので、constつけないでねーって感じで怒られる？のだと思っています。

じゃあ、const外せばええやんってなるんですが、今度はenum側（TabItemクラス）の問題でconstじゃない値を設定できないので解決できないって感じです。

自分は無理やりもう一つ上にconst宣言のクラス作ったのですが、徳田さんにレビュー指摘いただいたので対応策を聞こうと思っています～。

**Comment by susatthi** [comment]
通りすがりのすさです。

dummyListのfinalをstatic const にすればよさそう、と思いました！

**Comment by Romu1273x** [comment]
これダミーデータ（makeDummyItemの引数で使用しているデータ）をモデル層に書いて、それをBookShelfPageクラスで参照してグリッドで生成しているWidget（makeDummyItem）を動的に作れば通らないですか？
間違ってたらすみません。

**Comment by Romu1273x** [comment]
あ、すささんの方法で行けたらそれが楽で良さそうですね！

**Comment by Romu1273x** [comment]
適当に書きましたが、言いたかったのはこういう事です。
![スクリーンショット 2022-08-06 18 27 50](https://user-images.githubusercontent.com/74139918/183243202-facaa65e-25ae-43a8-ae5e-1a372d00648e.png)

**Comment by Romu1273x** [comment]
適当に書きましたが、言いたかったのはこれです。
一応、以下のコードでエラー消えました。（動かしてはないです。）
![Uploading スクリーンショット 2022-08-06 18.32.40.png…]()

**Comment by Romu1273x** [comment]
```
import 'package:flutter/material.dart';
import 'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

class Book {
  double height;
  double width;
  Color color;

  Book(this.height, this.width, this.color);
}

List<Book> dummyList = [
  Book(200, 100, Colors.red),
  Book(200, 100, Colors.red),
  Book(200, 100, Colors.red),
  Book(200, 100, Colors.red),
  Book(200, 100, Colors.red),
];

/// 本棚画面クラス
class BookShelfPage extends StatelessWidget {
  const BookShelfPage({Key? key}) : super(key: key);

  /// ダミー用Widget作成用メソッド
  /// [height] 高さ
  /// [width] 横幅
  /// [color] 色
  /// return 高さ*幅サイズのカラー設定済みContainer
  Widget makeDummyItem(double height, double width, Color color) {
    return InkWell(
      onTap: () {
        // TODO タップ時の作品詳細画面遷移
      },
      child: Container(
        margin: const EdgeInsets.all(8),
        height: height,
        width: width,
        color: color,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        centerTitle: true,
        title: const Text('絵本の棚'),
      ),
      body: SingleChildScrollView(
        child: StaggeredGrid.count(
          crossAxisCount: 2,
          children: List.generate(
            dummyList.length, // TODO ここで利用するリストはFirebaseから取得した情報群
            (index) => makeDummyItem(dummyList[index].height,
                dummyList[index].height, dummyList[index].color),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.add),
        onPressed: () {
          // TODO 検索一覧画面に遷移する
        },
      ),
    );
  }
}

```

**Comment by Romu1273x** [comment]
コピペ出来る様に上にコード貼っときます。

**Comment by Romu1273x** [comment]
あ、以下はタイプミスって追加されただけなので無視してください。
`import 'package:freezed_annotation/freezed_annotation.dart';`
