### ISSUE TITLE
リリース作業を調べてやること洗い出す

### ISSUE THREAD

**Issue by karokita** [pj-picbook/picbook#78]
## 概要

- リリース作業を調べてやること洗い出す

## 要件

- ◎TestFlightを今更まとめてみた
https://qiita.com/haseken_dev/items/8c094b44c7e67836b74d
先行テスター募集でやるのもあり？

[ iOS] App Store Connect の Public ベータで公開/TestFlight 
 [Android] Firebase App Distribution

- ◎iOS

- Apple Developer Appを使用した登録と本人確認
  - https://developer.apple.com/jp/support/app-account/#:~:text=%E3%82%BF%E3%83%83%E3%83%97%E3%81%97%E3%81%BE%E3%81%99%E3%80%82-,%E7%99%BB%E9%8C%B2%E3%81%AB%E4%BD%BF%E7%94%A8%E3%81%97%E3%81%9FApple%20ID%E3%81%A7%E3%82%B5%E3%82%A4%E3%83%B3%E3%82%A4%E3%83%B3%E3%81%97,%E3%83%9C%E3%82%BF%E3%83%B3%E3%82%92%E3%82%BF%E3%83%83%E3%83%97%E3%81%97%E3%81%BE%E3%81%99%E3%80%82

- （2022年版）iOSアプリをAppStoreで公開する手順まとめ
  - https://zenn.dev/moutend/articles/feebf0120dce6e6426fa

- （手順1）アプリのスクリーンショットを撮影する
- （手順2）App IDを作成する
- （手順3）アプリをAppStore Connectに登録する
- （手順4）アプリの一般情報を編集する
- （手順5）App Informationを設定する
- （手順6）Pricing and Availabilityを設定する
- （手順7）App Privacyを設定する
- （手順8）アプリをアップロードする

- ◎Android

- https://dev.classmethod.jp/articles/android-app-how-to-release/
- 事前準備 - Google Play Developer への登録
- Android アプリを配布するには25ドルの Google Play Developer への登録が必要です。登録料は25ドルで、月額とかではなく初回に支払う
  - 	1	アプリの apk ファイルを作成する
  - 	2	アプリ情報を登録する
  - 	3	apk ファイルをアップロードする
  - 	4	価格と販売/配布地域を設定する
  - 	5	公開し、2〜3時間後にリリース完了！

## 期限

- 2020/08/10

## 親ストーリー

なし

**Comment by karokita** [comment]
**リリースからユーザーフィードバック回収までの流れ**
  - [ ] 知り合いづてorSNSで依頼かける。OKもらったら公式アカウントの登録を促す
  - [ ] アプリを利用してもらう。利用手こずった場合は、アカウントからサポート
  - [ ] 利用した後、アンケートを送付/インタビュー実施


**iOS**
- [ ] Apple Developer Program登録　https://developer.apple.com/jp/programs/
- [ ] Apple store connectでアプリを作成　https://appstoreconnect.apple.com/login?targetUrl=%2Fapps&authResult=FAILED
- [ ] グループ作ってパブリックリンクを作成　https://qiita.com/toshi586014/items/3c79a2a8565b4382fb1e

**Android**
- https://firebase.google.com/docs/app-distribution/android/distribute-console?hl=ja

**準備するもの**
- [ ] アプリアイコン
- [ ] 説明文
- [ ] LINE公式アカウント作る　https://www.linebiz.com/jp/column/technique/20190830/
- [ ] 説明用のLPかnotionか何かページを作る

**Comment by tokku5552** [comment]
そういえばfirebaseの設定ファイルで思い出したんですが、初回リリースってfirebaseのプロジェクトはprd環境でリリースしますよね？flavor分けの対応をそれまでにやらなきゃいけません 😓

**Comment by karokita** [comment]
証明書
https://developer.apple.com/jp/support/certificates/

App Store で iOS アプリ公開に必要な「Certificates Identifiers & Profiles」について情報整理する
https://qiita.com/c_tomioka/items/af5942b7031962c3faff

**Comment by karokita** [comment]
@kawadon780 リリース達人かわどさんにご質問です！
アンドロイドで署名つきのAPKファイルを作成したいですが詰まってます。

どのサイトにも下記のような記述があるのですが、私のandroid studioには該当のメニューが存在せずで...

>メニューバーで、[Build] > [Generate Signed Bundle/APK] をクリックします。
(サイト例　 https://ramble.impl.co.jp/618/)


[私のAndroid studioの画面]
![S__3514385](https://user-images.githubusercontent.com/96728192/188271570-da8c4b76-3e63-425f-9f87-a05693010be7.jpg)

- 何か設定を変えるとAndroid studio上に出現する
- あるいは別のやり方で署名つきファイルを作成できる

上記のどちらか、方法ご存じでしょうか...？

**Comment by kawadon780** [comment]
@karokita とりあえず署名付きのapk作るだけなら、そちらのBuild apkで問題ないです。
ただし、恐らく設定たりずエラーがでるか、もしくは指定したかった署名ができてない可能性はあると思います（デフォルトだとdebug用のjksファイルで署名されちゃうと思います）

また、リリースするには現在は「App Bundle」でないとダメです。

上記の問題も気になる所ですが、まずは以下２点できてますでしょうか？

apkを作成できるか？
aap bundleを作成できるか？



あと、androidStudioでやってもいいですがコンソールコマンドで作成する方法もありまして、vscodeで開発する場合はそちらのやり方を採用する事があります(flutter build apk)

**Comment by karokita** [comment]
@kawadon780 
ご確認ありがとうございます！
はい、下記のような形でファイル作成できています。

app-release.apk
app-release.aab

おお、なるほど。bundleでないとリリースできないのですね。
そしてVScodeでもいけるんですね。ふむふむ。。。

bundleだとすると、この手順通りにやると良い感じですかね。
https://qiita.com/uhooi/items/3bee37d763642c703738
一度試してみたいと思いました！

**Comment by kawadon780** [comment]
@karokita 
返答遅れましてすみません。

作れてるならよかったです。
やる事は以下です。

１、秘密鍵を生成

２、その鍵で署名

ってだけなんですが、これよく考えたら自分のflavorの作業と被るんですよね。。ちょっと進め方どうしようかと悩みますね。
ちょっとgraldeの作業はむずかしいので自分の方でやった方がいいかもしれません。

**Comment by karokita** [comment]
@kawadon780 
ありがとうございます！実は下記記事で解決しそうで、作業進行できている感じです。
https://virment.com/how-to-fix-missing-generate-signed-bundle-menu-for-flutter-app/

flavor分けの作業を進める上で、むしろここが進んでないのが作業上ボトルネックになってるとかあればお知らせください！

**Comment by kawadon780** [comment]
@karokita 
承知しました！とりあえず任意の鍵で署名できているので問題ないです！
被るかもーとかの作業も一旦気にしないで作業しようと思うのでダイジョブです！
