### ISSUE TITLE
新規登録画面の作成(メールアドレス）

### ISSUE THREAD

**Issue by tokku5552** [pj-picbook/picbook#8]
## 概要
![スクリーンショット 2022-07-23 16 49 59](https://user-images.githubusercontent.com/96728192/180596002-d52e44a2-b153-416b-9330-7f533fb96f10.png)
- メールアドレスによる新規登録画面の作成

## 要件

- Appbar
  - テキスト
    - 会員登録
- 入力フォーム
    - なまえ入力欄
      - テキスト
        - なまえ
      - フォーム
        - hinttext  ご自身もしくはお子様の名前をご入力ください
    - 生年月日入力欄
      - テキスト
        - 生年月日
      - フォーム
        - hinttext  xxxx/xx/xx
      - 備考
        - 生年月日選択はこの記事のイメージです！　https://garmi.blog/2020/03/01/flutter-cupertinodatepicker%E3%81%A7%E6%97%A5%E4%BB%98%E3%81%AE%E3%81%BF%E9%81%B8%E6%8A%9E%E3%81%97%E3%81%9F%E3%81%84/
  - メールアドレス入力欄
    - テキスト
      - メールアドレス
    - フォーム
      - hinttext  メールアドレスを入力してください
- パスワード入力欄
    - テキスト
      - パスワード
    - フォーム
      - hinttext  パスワードを入力してください
- 登録ボタン
  - テキスト
    - 登録する
  - 遷移先
    - 成功→本棚画面へ
    - 失敗→ポップアップ表示　※要検討
- 注意書き
  - テキスト
    - 「登録する」ボタンを押すことで、[利用規約]※1に同意したものとみなします。
  - 遷移先
    - ※1 利用規約へ遷移

## 期限

- 例：2020/08/01

## 親ストーリー

#6

**Comment by Ta23ka98** [comment]
新規登録画面のUI作成について、2点ほど共有しておきます🙋

1. signinディレクトリを、signupディレクトリに変更
2. ブランチ名を、feature/#_signup_pageにしてしまった
(UIという単語が抜けてしまった。完了後はちゃんとブランチを削除→機能作成時はちゃんと別名でブランチを作ります🙇)

**Comment by Ta23ka98** [comment]
@karokita 
ThemeDataの影響か、AppBarのテキストウィジェットの色がおかしくなっているみたいです🙋
(ログイン画面作成時に気づいたので、そちらはTextStyleにて白色に設定してあります)
<img width="351" alt="スクリーンショット 2022-08-03 12 48 54" src="https://user-images.githubusercontent.com/79580546/182520245-57e06f8a-32ca-4802-8e63-7a09229c14d3.png">
