### ISSUE TITLE
新規登録画面の生年月日/名前部分の登録

### ISSUE THREAD

**Issue by pj-picbook** [pj-picbook/picbook#85]
## 概要
![スクリーンショット 2022-07-23 16 49 59](https://user-images.githubusercontent.com/96728192/180596002-d52e44a2-b153-416b-9330-7f533fb96f10.png)

- 新規登録画面の生年月日/名前部分を登録(全コレクションの生成も含む）

## 要件

- bookshelfに持たせる
- ex.ownerName、ownerAge

## 期限

- 2020/08/15

## 親ストーリー

#6

**Comment by tokku5552** [comment]
@kawadon780 
お手すきでいいんですが、現在のBottomNavigationPageの仕様ちょっと教えてもらって良いですか？
具体的にはGlobalKeyを使用している理由と、WillPopScopeでラップしているのはなぜか？というところです。
ログイン後、一回ログアウトして、再度ログインすると、GlobalKeyが重複しているとのことで落ちてしまいます 🤔

**Comment by kawadon780** [comment]
@tokku5552 
すみません！履歴みるとRomuさんが実装しているみたいでして、採用している理由はわからないです。

NavigatorStateを使ったBottomNavigationBarの画面遷移を使うとバックキーも対応できるので便利からなのかなーと予想はしていますが。

**Comment by tokku5552** [comment]
@kawadon780 失礼しました勘違いしていました 😅 
@Romu1273x 
改めてお手すきで教えていただいてもよろしいでしょうか？

> お手すきでいいんですが、現在のBottomNavigationPageの仕様ちょっと教えてもらって良いですか？
具体的にはGlobalKeyを使用している理由と、WillPopScopeでラップしているのはなぜか？というところです。
ログイン後、一回ログアウトして、再度ログインすると、GlobalKeyが重複しているとのことで落ちてしまいます 🤔

**Comment by Romu1273x** [comment]
@tokku5552 
記事参考に実装したので、理解して切れている訳では一応以下が理由になります。

- GlobalKeyについて
NavigatorStateでタブごとの状態を管理していて、その際にどのStateかを特定するためにGlobalKeyを使ってます。

- WillPopScopeのラップについて
Andoridのバックボタンはバックグランドまで戻ってしまうので、ちゃんと遷移前の画面がある場合はその画面に戻るように制御するためです。

**Comment by Romu1273x** [comment]
@tokku5552 
> 【対応案】
> ログアウトする際に存在するNavigatorStateを削除する。

上記ですが、`mypage.dart`でログアウトして`FirstPage()`に遷移してますが、それを以下に変えるとNavigatorStateも消えませんか？（試してないので上手く行くか分かりません。）
`Navigator.push`　→　`Navigator.pushAndRemoveUntil`
