### ISSUE TITLE
マイページにデータを表示させる

### ISSUE THREAD

**Issue by pj-picbook** [pj-picbook/picbook#86]
## 概要

![183979657-5a312ab4-ac7e-4a1e-b4c3-b9fe30f64a2f](https://user-images.githubusercontent.com/96728192/184532143-a3c98271-126d-4cbe-97e1-7faba96ebd3e.png)

マイページの画面UIとデータを繋ぎ込む

## 要件

- ユーザー情報
  - なまえ
    - 登録した名前が表示
  - よんだえほん
    - 読んだ絵本の冊数が表示
  - 年齢
    - 年齢が表示
  - 登録日
    - 登録した日にちが表示
- ログアウト
  - ログアウトする

※アイコンはコメントアウトで非表示

## 関連タスク

- #29 
- #30

**Comment by Ta23ka98** [comment]
@tokku5552 
こちらに着手したいのですが、このようなエラーが出ています🤔
エラー文で調べると、セキュリティールール絡みらしいので相談させて頂きました。

Authにて会員登録は確認できましたが、コレクションが作成されていないようです。

<img width="1397" alt="スクリーンショット 2022-08-17 14 25 50" src="https://user-images.githubusercontent.com/79580546/185077684-d03e44ba-2ea2-4818-ba52-f6316e354212.png">

**Comment by tokku5552** [comment]
@Ta23ka98 
すみません、すぐ確認できないんですが、ブランチはdevelopの最新の変更を取り込んでいますか?
ローカル環境の問題じゃなさそうなら、一度firebaseのコンソールで実際の動作をテスト出来るので試してもらってもよいでしょうか？

**Comment by Ta23ka98** [comment]
@tokku5552 
改めてFirestoreを確認したところ、ちゃんとコレクションに追加されていました...
何を勘違いしたのか...お騒がせしてすみません🙇

ただサブコレクションについては、やはり追加されていないようです🤔
こちらは追加される想定なのでしょうか？

エラー文が`The caller does not have permission to execute the specified operation.`と出ているので、サブコレクションの作成のことを言っている気がします。
(ブランチのコミット遅れについては、昨夜にdevelopを最新→そこから新しいブランチを作っているので問題ないと思います)

**Comment by Ta23ka98** [comment]
コンソールでテストした結果、` && isValidUser(request.resource.data);`でエラーが出たみたいです。

<img width="1178" alt="スクリーンショット 2022-08-17 20 58 07" src="https://user-images.githubusercontent.com/79580546/185113115-4703d8dc-6700-4d99-9f14-de7c88376473.png">

**Comment by tokku5552** [comment]
@Ta23ka98 
本当ですね、、、すみません直します、、、

**Comment by tokku5552** [comment]
@Ta23ka98 
こちら #100 にて修正完了&デプロイも完了したのでなおっていると思います！
中途半端になっていたユーザーとコレクションはきれいにしておいたので、改めて登録してみてください！

**Comment by Ta23ka98** [comment]
@tokku5552 
修正ありがとうございました！
・会員登録後の画面遷移
・マイページでのuidの表示
・Firestoreでのコレクション、サブコレクションの作成
を確認できました🙌

ここからは自分のタスク範囲の確認なのですが...
・CupertinoDatePickerで生年月日を取得できるようにする
・取得した生年月日をbookshelfに登録する(初回登録時の本棚)
・登録された生年月日および年齢を計算し、マイページに表示する
という感じで間違いないでしょうか🤔

----
これはまた別のエラー(？)なのですが...
ビルド時に同様のエラーが出るようです。ログイン状態の監視関係のものでしょうか？

念のため、報告だけさせていただきました🙋
(スクショのコードは前回の確認時のもので、とくに開発はしていないです)
<img width="1394" alt="スクリーンショット 2022-08-18 12 21 13" src="https://user-images.githubusercontent.com/79580546/185286945-7dfabb86-61ec-4b0c-bde1-5a4059c402aa.png">

**Comment by tokku5552** [comment]
@karokita 
> ここからは自分のタスク範囲の確認なのですが...
・CupertinoDatePickerで生年月日を取得できるようにする
・取得した生年月日をbookshelfに登録する(初回登録時の本棚)
・登録された生年月日および年齢を計算し、マイページに表示する
という感じで間違いないでしょうか

こちらどうでしょう？私は概ねあっているかなと思っています。

> また会員登録画面がRenderflex overflowしており

これAndroidとかで出るやつですかね？ログイン画面と同じようにというのはどういう挙動でしょうか？ 🤔

**Comment by Ta23ka98** [comment]
@tokku5552 
すみません。見辛いですが、3つほどスクショを載せてあります🙋
(会員登録画面/ログイン画面のビフォー、アフター)

---
会員登録画面のRenderflex overflowは、こんな感じのエラーです
ソフトウェアキーボードが出たタイミングで、このSignUpPageの画面に入りきらなくなるようです。
(シミュレータの初期設定だと出ないですが、Simulator→I/O→Keyboard→Toggle Software Keyboardで出せます)
<img width="349" alt="スクリーンショット 2022-08-19 11 40 50" src="https://user-images.githubusercontent.com/79580546/185531389-89b56976-b6a3-4eaa-a585-ba0920a1377b.png">

---
ログイン画面の挙動については、
①こちらの画面のフォームなどが...
<img width="351" alt="スクリーンショット 2022-08-19 11 40 21" src="https://user-images.githubusercontent.com/79580546/185531976-25e2d2e6-ce29-4d16-ac9d-17dd89757243.png">

②このように、キーボードの出現に合わせて小さくなる仕様のことです
(以前に何度か調べたことがあるのですが、同様のやり方が見つからなかったです🤔)
<img width="352" alt="スクリーンショット 2022-08-19 11 40 34" src="https://user-images.githubusercontent.com/79580546/185532186-2341659c-a2bf-4232-a078-150702a6a38f.png">

**Comment by karokita** [comment]
@tokku5552 @Ta23ka98 

ありがとうございます！タスク範囲ですが、下記ご返答になります。

・CupertinoDatePickerで生年月日を取得できるようにする→はい、そうです！
・取得した生年月日をbookshelfに登録する(初回登録時の本棚)→です🙆‍♀️
・登録された生年月日および年齢を計算し、マイページに表示する→ここだけ、BookshelfがcreatedされたDate Timeを持ってくるイメージでした

**Comment by Ta23ka98** [comment]
@karokita 
> ここだけ、BookshelfがcreatedされたDate Timeを持ってくるイメージでした

すみません、今ちょうど実装していたので気づきました😅
仰るとおり、表示するのは生年月日ではなく登録日でした。

確認ありがとうございました！🙌

**Comment by tokku5552** [comment]
@Ta23ka98 
ログイン画面と同様にというよりは、ログイン画面では現状エラーが確認できないが、ってことですかね？
おそらく端末によっては同じことが起こりうるので同時に対処するのが良いかと思います！
単純に`SingleChildScrollView`でラップするだけじゃダメそうでしょうか？

**Comment by Ta23ka98** [comment]
@tokku5552 
徳田さんがログイン画面を修正して下さったのかと勘違いしていました😅
「その修正みたいに、自分も会員登録画面を修正できたらよさそう」と思っていた感じです。ややこしくてすみません...🙇‍♀️

とりあえず、ログイン画面/会員登録画面の両方を、色々と試して修正してみます🙋
